---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: private-gateway
spec:
  addresses:
  - value: istio-privategateway.istio-gateways.svc.cluster.local
    type: Hostname
  gatewayClassName: istio
  listeners:
  - name: http
    hostname: "*.${CLUSTER_DOMAIN}"
    protocol: HTTP
    port: 80
  - name: https
    hostname: "*.${CLUSTER_DOMAIN}"
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - name: abasitt-tech-secret
    allowedRoutes:
      namespaces:
        from: All
  - name: tcp-cnpgcluster16
    protocol: TCP
    port: 5432
    allowedRoutes:
      namespaces:
        from: All
      kinds:
      - kind: TCPRoute
