---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app multus
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3

  values:
    controllers:
      multus:
        type: daemonset
        initContainers:
          cni-plugins:
            image:
              repository: ghcr.io/buroa/cni-plugins
              tag: 1.6.2@sha256:b8bf519bda14762782525bb5607d852a76c4bf0da5ffbd8ca021469818ccd8f8
        containers:
          multus:
            image:
              repository: ghcr.io/k8snetworkplumbingwg/multus-cni
              tag: v4.2.2@sha256:7591a27cd28eeafd6dfb197618b06dabd9446a7026164b9b21fee67adc925761
            command:
              - /thin_entrypoint
            args:
              - "--multus-conf-file=auto"
              - "--multus-autoconfig-dir=/host/etc/cni/net.d"
              - "--cni-conf-dir=/host/etc/cni/net.d"
              - "--multus-master-cni-file-name=10-calico.conflist"
              - "--multus-log-level=verbose"
              - "--multus-log-file=/var/log/multus.log"
              - "--cleanup-config-on-exit=true"
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 32Mi
            securityContext:
              privileged: true
    defaultPodOptions:
      hostNetwork: true
      tolerations:
        - operator: Exists
          effect: NoSchedule
        - operator: Exists
          effect: NoExecute

    persistence:
      etc-cni-net-d:
        type: hostPath
        hostPath: /etc/cni/net.d
        globalMounts:
          - path: /host/etc/cni/net.d
      opt-cni-bin:
        type: hostPath
        hostPath: /opt/cni/bin
        globalMounts:
          - path: /host/opt/cni/bin
    serviceAccount:
      create: true
      name: *app
