---
kubernetes:
  children:
    master:
      vars:
        ansible_user: k8s
      hosts:
        k3s-m1:
          ansible_host: 192.168.30.21
    #    k3s-m2:
    #      ansible_host: 192.168.30.102
    #    k3s-m3:
    #      ansible_host: 192.168.30.103
    worker:
      vars:
        ansible_user: k8s
      hosts:
        k3s-m2:
          ansible_host: 192.168.30.22
