---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pgadmin-secret.sops.yaml
  - ./helmrelease.yaml
  - ./httproute-private.yaml
  - ../../../../templating/volsync
