apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secret
stringData:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:j5eoppkPv20JRrfd0OkdlhoybYNq,iv:rz0wx0sRk2V+Dh6D9OsS31xahdpfxTS5oehY1OGJMWw=,tag:5Zp9cB30mBORnLj0Ef7hng==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:BPcFR7JoTPLbJw8gFx8RgcSXVsI=,iv:qEUDwn3NHezHt8bp5cIOvP9zKeC4ikoEcwMNWutNjKA=,tag:gXQ3n74RrjlJRP/ColTifQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w8pq3mz7lhcnf3ajppkf9ee9j7ywapkenrads9nk3yjm08szd4rqwy3r67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQTdETG05U2RwMCtYWFZG
            eXcySnNVSE5UeG9SWXNkTlNmRVNtRU94dVFvCmZ4OGdoYU1ycStGRE5TVGU4SkNY
            K1JPS2d1dDlHY0hXSjZsek5USzE2Tm8KLS0tICs3WmNab1Y0bjhWOC90UFltTlRJ
            SHQxZmtXeGhadU1BeEF6UEVadHVGVjQK2JypgghHwuBDE29MhtKieSGK6hbShF7R
            LHacj+5hFXA1izqVUzs7gFQSjUgyfwUuUpWNKIWerTiKbuF4tJWJGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-08T13:23:49Z"
    mac: ENC[AES256_GCM,data:QJ0M4mRcMZCvGNYLxrnoHtEW02mQ3JWIyQNmLY7kk2hrA8QaItmRDpooHhqhk1dSCDCirebricwat7wEj6KpZ7kCFUu+/YpgN3jxA6bdYI+sPdcn8zVWeB6i/NBBxD6HU1I6WTJ9NnUEFgmLcpUGRgdYOC/MmRw264exSByMVCs=,iv:43Ee+Q1jFrr2jEUcuTaSjaln+J5UicQ0l0R2xgyKCDo=,tag:dmf6HYlMimq11dLH4cQmOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
