---
controllers:
  calibre-web:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: ghcr.io/bjw-s/calibre-web
          tag: 0.6.24@sha256:57fc39bbc7a49ee48f50b8691b47d768c130fd6e8569ec17bde051eae5beddd6
        env:
          CACHE_DIR: /cache
          TZ: ${TIMEZONE}
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
        resources:
          requests:
            cpu: 5m
            memory: 250M
          limits:
            memory: 300M
    pod:
      securityContext:
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
        fsGroupChangePolicy: "OnRootMismatch"
service:
  app:
    controller: calibre-web
    ipFamilyPolicy: PreferDualStack
    ports:
      http:
        port: 8083
route:
  app:
    parentRefs:
      - group: ""
        kind: Gateway
        name: external-gateway
        namespace: istio-gateways
    hostnames:
      - books.${SECRET_DOMAIN}
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /
        backendRefs:
          - kind: Service
            port: http
            name: app
            weight: 100
#ingress:
#  app:
#    className: external
#    #annotations:
#      #external-dns.alpha.kubernetes.io/target: external.${CLUSTER_DOMAIN}
#      #hajimari.io/icon: mdi:chart-bar
#      #gethomepage.dev/enabled: "true"
#      #gethomepage.dev/group: Media
#      #gethomepage.dev/name: Calibre
#      #gethomepage.dev/icon: calibre.png
persistence:
  config:
    existingClaim: ${VOLSYNC_CLAIM}
  cache:
    type: emptyDir
    globalMounts:
      - path: /cache
  media:
    existingClaim: media-nfs
    globalMounts:
      - path: /media
