---
# https://rancher.com/docs/k3s/latest/en/installation/install-options/agent-config/
# https://github.com/PyratLabs/ansible-role-k3s

k3s_control_node: false
k3s_agent:
  node-ip: "{{ ansible_v6host }},{{ ansible_host }}"
  #node-ip: "{{ ansible_default_ipv6.address }},{{ ansible_host }}"
  pause-image: registry.k8s.io/pause:3.10
  kubelet-arg:
    - "image-gc-high-threshold=55"
    - "image-gc-low-threshold=50"
    - "node-ip={{ ansible_v6host }}"
