---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./intel-gpu-device.yaml
  - ./network-interfaces.yaml
#  - ./nesdr-rtl-sdr-device.yaml
