---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/nfd.k8s-sigs.io/nodefeaturerule_v1alpha1.json
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: network-interfaces
spec:
  rules:
    - name: bond-interface
      labels:
        feature.node.kubernetes.io/network-interface.bond: "true"
      matchFeatures:
        - feature: network.device
          matchExpressions:
            name: { op: In, value: ["enp1s0", "enp2s0"] }
    - name: single-interface
      labels:
        feature.node.kubernetes.io/network-interface.en0: "true"
      matchFeatures:
        - feature: network.device
          matchExpressions:
            name: { op: InRegexp, value: ["^eno[0-9]+$"] }  # Matches eno1, eno2, etc.
