---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/nfd.k8s-sigs.io/nodefeaturerule_v1alpha1.json
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: network-interfaces
spec:
  rules:
    - name: bond-interface
      labels:
        feature.node.kubernetes.io/network-interface.bond: "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            class: { op: In, value: ["0200"] }
            vendor: { op: In, value: ["8086"] }
