autoscaling:
  minReplicas: 1
  maxReplicas: 1
service:
  annotations:
    metallb.universe.tf/loadBalancerIPs: ${METALLB_ISTIOINGRESS_V6ADDR},${METALLB_ISTIOINGRESS_V4ADDR}
  externalTrafficPolicy: "Local"
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  ipFamilyPolicy: RequireDualStack
  ports:
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

volumes:
  - emptyDir: {}
    name: workload-socket
  - configMap:
      defaultMode: 420
      name: istio-ca-root-cert
    name: istiod-ca-cert

volumeMounts:
  - mountPath: /var/run/secrets/workload-spiffe-uds
    name: workload-socket
  - mountPath: /var/run/secrets/istio
    name: istiod-ca-cert
# affinity:
#   # This podAntiAffinity ensures ingress controllers are not scheduled on the same node
#   podAntiAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#     - labelSelector:
#         matchExpressions:
#         - key: istio
#           operator: In
#           values:
#           - ingressgateway
#       topologyKey: kubernetes.io/hostname
