autoscaling:
  minReplicas: 1
  maxReplicas: 2
service:
  annotations:
    metallb.universe.tf/loadBalancerIPs: ${METALLB_ISTIOINGRESS_V6ADDR},${METALLB_ISTIOINGRESS_V4ADDR}
  externalTrafficPolicy: "Local"
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  ipFamilyPolicy: RequireDualStack
  ports:
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
# affinity:
#   # This podAntiAffinity ensures ingress controllers are not scheduled on the same node
#   podAntiAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#     - labelSelector:
#         matchExpressions:
#         - key: istio
#           operator: In
#           values:
#           - ingressgateway
#       topologyKey: kubernetes.io/hostname
