---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: babybuddy
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3

  values:
    controllers:
      babybuddy:
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1

        containers:
          app:
            image:
              repository: lscr.io/linuxserver/babybuddy
              tag: 2.7.0@sha256:0172d93d7d712797a55d3b3bf844ffeda459d1a15b55a7343ac7eed3b5ab4760
              pullPolicy: IfNotPresent
            env:
              TZ: ${TIMEZONE}
              PUID: 2000
              PGID: 2000
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 15m
              limits:
                memory: 256Mi

    service:
      app:
        controller: babybuddy
        ports:
          http:
            port: &port 8000

    route:
      app:
        parentRefs:
          - group: ""
            kind: Gateway
            name: private-gateway
            namespace: istio-gateways
        hostnames:
          - "{{ .Release.Name }}.${CLUSTER_DOMAIN}"
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - kind: Service
                port: http
                name: app
                weight: 100

    persistence:
      config:
        existingClaim: babybuddy-config
