apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:G3uWK2mp7wlbyl+a,iv:94RsxLvhIWPLL9xwdguAHNySBYxsotgsYKAU9P12DnM=,tag:jFjInxUnFm9POh6Tpo/gLA==,type:str]
    SECRET_ADMIN_EMAIL: ENC[AES256_GCM,data:pcYnZYmcXo43nrAHDJwgNFFtLhSq,iv:M61xmHz+rc+muPuW5+KvDr1QdEDVsvjsITzxKYR+q0U=,tag:5S+T8AETYW/NzMyUduOwlA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:cVNVp7Lj9Krl+8si0q9Vv9bHByn2,iv:4PwdZXGJQV5nb5GTIj/tNjnaPd8jCS6ay1x7fu4Gsbg=,tag:08sf0NhcCDkLn7ZMDsMKRQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:otvFmVB7S+16Ayap3RPgi9oYBXbhg9kfE3AYnmhzvI8R0ROGFW9gUg==,iv:2lN8uiZm9vez47FvyUwPxU9UnjdZJz+uix30gXwai/U=,tag:zFF5oloY6w9u8MxNV2v1Uw==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:lJZGfUq65/tdQI0lO0eZpRJNc04XWRwSlsQ766V296wX4cc24g==,iv:4lamFruDdcKqReAALzWkuvpGnMLa3mnIEYMJYYVjoQ4=,tag:Df2d6iEoY4UafyESl0wAuA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:OI1kgBxglWKFn+B8aB5SLHhojx31snw7/wpFTpBp,iv:zlrAM0VhtcqJrJsAHRm9Olohv6VOdkO9HVHKX6s8RzY=,tag:v448l1MdwwecXWHnlCsoqg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:egG0Sf233pI+fE9a9MRBIyNIdLI=,iv:l4KikSTF695d4QoTeIeZXDwnR1rXiIZ1yOTTFJvVAU4=,tag:0nUA5IkPWjHsih3VTbORjA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:okVvSrqPSa0FEDYcg3Z75nBwLftHRQd6HV0ubjn/1Y13iI2O3u+2VA==,iv:POqYI6ARCy4mBTWRjDfu4B1NU8rXIyo15NO0OsoBbqQ=,tag:OoMECoLnfGC4WZz0cLHE3w==,type:str]
    MINIO_ENDPOINT: ENC[AES256_GCM,data:rqmQAAfCz17zLIgC/BLE0Vh+/v/58yPAYps=,iv:ZxR6jDCal6AMVPsFEhi15WTnukisq3cK/m3Sx0uqj1I=,tag:N5xsTckqZPPXEBHm1WOPBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w8pq3mz7lhcnf3ajppkf9ee9j7ywapkenrads9nk3yjm08szd4rqwy3r67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSjAxRnRyUkM2amNJNkR1
            STFZVkV1UkNmUFdlKzBlVVpPWUxwTGxlZGtRCis4TWNHajJHdFd4QVN6bmxWYUlL
            cXBmMWZ1S1JLWjZ3ODZHVGdRUldtU3cKLS0tIHFnbEVISXZDbFkrbUZXZmdLc1Y1
            TjN5OTZ3TmJzcEtIdC9mQVNoUEJjTUkKkdjCD64OJ7xiiIme2sVZ6v8GLlCYvA8d
            2Mk/jyrnNpUJmW3OAqC7289eKRG12H5w4WotcW2asBgdWHxokuw3eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T02:19:07Z"
    mac: ENC[AES256_GCM,data:dBffVsF5/4bVASjjZlfVDYYhzsebI4ROgLiC6YVOYKFBfzxzJunjXgtJFJ1pojmF40tkPJlfwsVus9opxa9XYaHoUf7DaXkNNG7Y/Du/4vUo9gwrIuDs1HsgkcpahOH06+6tKYJYu+pKcMP3DF/XBoqvDV5gxNRNV4g8P8rKFtw=,iv:hDZL1Qz191W/Qy40inbtAHx4AvxUzwMZpQwaOiUHV4U=,tag:+FVB/zqzsenl8ymPoZb26w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
