apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:WofkbIHoX61/o419,iv:pv+pcAc/Xjlb+s/WGimyh3J89ytVMBqJYnOuGnEhRvE=,tag:ItQGz1xnulhFg209+AzNAg==,type:str]
    SECRET_ADMIN_EMAIL: ENC[AES256_GCM,data:b7EbXXcFnNRuTw9C67BqZlN1QwE9,iv:5iTi0fKmQsFIDUTSJLsSAtZ4EdZtCgtbCueLQIu3MOw=,tag:p4XozXK1stZvw4sOzrhF/Q==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:yw5iwN/ifXqWKEIYFo4+rzxBgx3U,iv:HP/97R8RRQ7rwluxv6rzRWk3+bnZpzSbxb/WzXQb8tc=,tag:o+55u8CV5ahgRUzZP/v7FA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:QY4/P6kz13Z4c0bxDQWfeHhCVWZ1bmaAvYoNkKpxO+AlAaQepkP/AA==,iv:iByxIK6lGB2GeNCsIz08LuYX0ASM4Gzgv+yR9F/xgjE=,tag:/KB05frpCGwqy/hAxtuvFg==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:Ku8ID6ZBSXiUJeX/TRumfZpVOdm2O5oc/us3pmq2K4La7Tlscg==,iv:NWmTY81mWxB3ovcwXd7hZnKR6OT7HJyQSHtBtK4ea1s=,tag:TBECBvFDQyrfpFpuijec1g==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:sFFr08d8za9gaoslQ3FRFY4hu5dRotqtwpudRJK6,iv:y3T5cWCK8WqsmtTEaWo0wkh9BGm8G4oVq7PG9C/4ntY=,tag:6Hq76oLl6FU+rxphwCmM2w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:QlWH3xEBsCJtObkgIhw9bd4OID0=,iv:Be6QQM4oY/s07xfW/bKtzXRIzKK6qYZ5AiwvlX/0d3I=,tag:H4yUjPZQ6NJ1r//kNYdReA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:iV8SGJczxqpoMtlckteyyF2NXzgdIP+TwGGbJoga32+2MRrb4kGJpg==,iv:NnjFYEmFGn949e69KE9eGM6F/ouKTLZOXcMIXU1yJTI=,tag:D7Gj3uvA0npEGr+ZNqMvww==,type:str]
    MINIO_ENDPOINT: ENC[AES256_GCM,data:IfcVRJurqgwzHmEkl0FJTazRROx0nxCL0g4=,iv:5oMODKhYfRsVc/eJEs8KOXLC7dpziA+u2Tu428b/cb4=,tag:aX4xUdmBVZK76a8OAvM2Ng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w8pq3mz7lhcnf3ajppkf9ee9j7ywapkenrads9nk3yjm08szd4rqwy3r67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycHBLVjRvRTQrT0RjaERp
            MUtiWXZ5STMwQ21GQ28wam03NnoyUWNuanhjCjhad2VBcmc2K1ZDS2xkdkdrV3kr
            ZDdzRTNISFU5Zks2NXFheVdhYWlyQ0EKLS0tIHZ5Nk1CcjJuZzdZNzhqNVVhY2w3
            WTloUUJXVCtmSkxHd0JvTUtNcUptSEkKp7sOcTAYNSnSegg152ZtwSH9FIfDjo0p
            1t1F8l3ryQzlXtar7lDrbT6/REAHeUlTbCahz855cJzjDY3n4wHc+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-19T13:16:47Z"
    mac: ENC[AES256_GCM,data:z8Fx87jEV0EXb3wIwDyfJvqVzmaZtUBe+e0eW+tZ9V5B1PCboSj/i9n1YEmfowIrlXnkrBrAZhkgW/Elc5COQtb16rDxwPS+x2cwcJw5MDfhD/PyYH08m0ZZn55r8VsLEqr6EQsc8+Wq600G9uczZ9ekvSkrBeUjVljtM7+IUJ4=,iv:XXUYM3/uFCI9KNsyC/TtvYzER5YW/Kkxx7PNte2M2l8=,tag:W9j36XG+rjtkI/95zmiYjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
