---
timezone: "Asia/Singapore"
github_username: abasitt
kubeapi_addr: "192.168.30.2"
cluster_cidr: "10.40.0.0/16"
cluster_v6cidr: "fd00:10:40::/56"
service_cidr: "10.96.0.0/16"
service_v6cidr: "fd00:10:96::/112"
coredns_v4addr: "{{ service_cidr.split(',')[0] | ansible.utils.nthhost(10) }}"
coredns_v6addr: "{{ service_v6cidr.split(',')[0] | ansible.utils.nthhost(10) }}"