---
timezone: "Asia/Singapore"
github_username: abasitt
kubeapi_addr: "192.168.30.2"
cluster_cidr: "10.54.0.0/16"
cluster_v6cidr: "2001:470:ee86:5400::/56"
service_cidr: "10.55.0.0/16"
service_v6cidr: "2001:470:ee86:5500:10:55::/112"
coredns_v4addr: "{{ service_cidr.split(',')[0] | ansible.utils.nthhost(10) }}"
coredns_v6addr: "{{ service_v6cidr.split(',')[0] | ansible.utils.nthhost(10) }}"