---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app microbin
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      microbin:
        containers:
          app:
            env:
              MICROBIN_DATA_DIR: /var/lib/microbin
              MICROBIN_PORT: 8080
            envFrom:
            - secretRef:
                name: microbin-secret
            image:
              repository: ghcr.io/vaskozl/microbin-bin
              tag: 2.0.4@sha256:8ff3e3f313a6c0c1efacb6abbb3cca56ff6466576b20cab7ebae06c29da48074
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              limits:
                memory: 100Mi
              requests:
                cpu: 10m
                memory: 10Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              readOnlyRootFilesystem: true
        statefulset:
          podManagementPolicy: Parallel
          volumeClaimTemplates:
            - name: data
              accessMode: ReadWriteOnce
              storageClass: openebs-zfs-hdd
              size: 200Mi
              globalMounts:
                - path: /var/lib/microbin
        type: statefulset
    defaultPodOptions:
      securityContext:
        fsGroup: 568
        runAsGroup: 568
        runAsNonRoot: true
        runAsUser: 568
        seccompProfile:
          type: RuntimeDefault

    service:
      app:
        controller: microbin
        ipFamilyPolicy: PreferDualStack
        ports:
          http:
            port: 8080

    route:
      app:
        parentRefs:
          - group: ""
            kind: Gateway
            name: external-gateway
            namespace: istio-gateways
        hostnames:
          - "mb.${SECRET_DOMAIN}"
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - kind: Service
                port: http
                name: app
                weight: 100