apiVersion: v1
kind: Secret
metadata:
    name: microbin-secret
stringData:
    MICROBIN_PUBLIC_PATH: ENC[AES256_GCM,data:EdAdNiXKW5nXkBkeu0hxxrirwBEkNfo=,iv:4b0NRxwmTOyklDSU/rnCIkIASuyuUpUAFP+GyUcQHUI=,tag:tVVKAcLvXYmEyGYFaLcqKw==,type:str]
    MICROBIN_SHORT_PATH: ENC[AES256_GCM,data:0ZZ8wo73mqVTconVV7yivHbhGf3QchA=,iv:tY7694EfpDKnyjoHw1hwnq5CMz9kxCpIfsQ7s94LSuM=,tag:TAhZI9ikHWGpapowttC5lA==,type:str]
    MICROBIN_READONLY: ENC[AES256_GCM,data:NvkDZA==,iv:NeEFkknJaPYqydUIfTEs3dUhHOiGUEnJoTkT4FFq6fk=,tag:vEcERapeS/OGjpLbBco+SQ==,type:str]
    MICROBIN_ADMIN_USERNAME: ENC[AES256_GCM,data:ZIwGEh4B,iv:Gw7B9bDa9OpFOtHMVrCaJ5bwsTey81nJ5gOGe3nw+FY=,tag:DI51+J0x7y/Tx6Pt78Kj/w==,type:str]
    MICROBIN_ADMIN_PASSWORD: ENC[AES256_GCM,data:XVmuZ1Ui1cQ=,iv:yyrMjqbQyKcC2tP2Y3n4ZMahYTzxPqR/Him6TmYmzdk=,tag:96sTlBrNYw09rqf2iifzkQ==,type:str]
    MICROBIN_UPLOADER_PASSWORD: ENC[AES256_GCM,data:5wc7vq2uhxY=,iv:DDPD8jFVnIoslIq2a494UOvP2rDNx/ZV6x6PLj4kQTQ=,tag:PEulqwcAGFfU7oHgXWMvdg==,type:str]
    MICROBIN_HIDE_HEADER: ENC[AES256_GCM,data:h1LzjQ==,iv:zRrVFaUUaZlnR66B2WaoCvUiH28xO0uAWZOEL9NeDe0=,tag:4SeR2hZGtejIZYodTAPGuA==,type:str]
    MICROBIN_HIDE_FOOTER: ENC[AES256_GCM,data:mPwSuw==,iv:kQe0f75+4BrNN5I1D8zWZEXF6QFbNCe/us/0mHaeSKk=,tag:BnUDi209nq4SCyoKQuRf0A==,type:str]
    MICROBIN_HIDE_LOGO: ENC[AES256_GCM,data:TrvPag==,iv:zHx2rsoU/LQnmyWY89VmIG+IAQNFHP6dCcm8CPXCidE=,tag:AtQtwgnYQYID0TVVnGgPmA==,type:str]
    MICROBIN_NO_LISTING: ENC[AES256_GCM,data:PNJcqg==,iv:6VMBmdL3kPMxc6fvrm4FkGAaYBzXRGNi+GHDua0DrSA=,tag:+pfdAofikHeW2UumRCQjkQ==,type:str]
    MICROBIN_ENABLE_BURN_AFTER: ENC[AES256_GCM,data:wc7EeA==,iv:b9CpQVB5N70tmQgGPWIV9++uclG/GRg7hrr0Mhi0toI=,tag:YuTjwQ+eWOsgW+bS2DnDSQ==,type:str]
    MICROBIN_WIDE: ENC[AES256_GCM,data:KEXnow==,iv:2WfWoHcUzdm9nmUbDi28MZov3rcw7Jj8yRInP8+1Ses=,tag:ENm57e4SpqpW8HHGyFzrQQ==,type:str]
    MICROBIN_ETERNAL_PASTA: ENC[AES256_GCM,data:vo62iw==,iv:5SFLPd/Mb0SmdRvPi/Pal/4TvvHKDALxHl/Tiz93l34=,tag:DXEFcsOzckRrCBrbJkTmVg==,type:str]
    MICROBIN_ENABLE_READONLY: ENC[AES256_GCM,data:0C7Xrg==,iv:qZRBIP9zUmt+b1NFbQj4pAnrA6Lxi+P1T8K1Gabq+Ac=,tag:MD/m/I1hH+rZBn6rNgNY4g==,type:str]
    MICROBIN_HASH_IDS: ENC[AES256_GCM,data:dMn1Ug==,iv:oPcwinb9f1FR3Cg71uG8iqb/KBq8seQztcmqisKGbwo=,tag:iT2HtiZkvhx7YW0IBW50mg==,type:str]
    MICROBIN_DISABLE_TELEMETRY: ENC[AES256_GCM,data:G1C+ZQ==,iv:DgabePEj9OIYtSD0FuEBbasb6EX4WllRT+yqE+ZSwqg=,tag:rhUOkzWRWyV366IareSFmQ==,type:str]
    MICROBIN_BIND: ENC[AES256_GCM,data:OOA=,iv:ycD5lB1rn8pZ7G07FQSFZxsdHTWkuCSo3H/riX+umJQ=,tag:mL4ZdsKjhsqbka3jfwgLnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w8pq3mz7lhcnf3ajppkf9ee9j7ywapkenrads9nk3yjm08szd4rqwy3r67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQTdETG05U2RwMCtYWFZG
            eXcySnNVSE5UeG9SWXNkTlNmRVNtRU94dVFvCmZ4OGdoYU1ycStGRE5TVGU4SkNY
            K1JPS2d1dDlHY0hXSjZsek5USzE2Tm8KLS0tICs3WmNab1Y0bjhWOC90UFltTlRJ
            SHQxZmtXeGhadU1BeEF6UEVadHVGVjQK2JypgghHwuBDE29MhtKieSGK6hbShF7R
            LHacj+5hFXA1izqVUzs7gFQSjUgyfwUuUpWNKIWerTiKbuF4tJWJGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-30T08:36:42Z"
    mac: ENC[AES256_GCM,data:sET+Taybi9d1lJIf8uQzV3e6zW9PRsr1qqpVaR5c8+Yufi8hVmRLUE4oj0ibcIdGXz4VpVGIdTVTcdSu2N2YzVZiddpkaarHyIE2O3tM7OdsP+/P9b0KhdmMTmzniL1H0O4F/07PGn8q0XP+Kqyx5iLLNMorPqRuMhXukAJl6Ss=,iv:m9+cZgsB1DLt4s9PoLeeRfEVhyfSEEX0VdTveUxcick=,tag:KlCEa+6Jl0ZwktMCn1JP9g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
