---
creation_rules:
  - path_regex: kubernetes(/.*)?/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1w8pq3mz7lhcnf3ajppkf9ee9j7ywapkenrads9nk3yjm08szd4rqwy3r67
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1w8pq3mz7lhcnf3ajppkf9ee9j7ywapkenrads9nk3yjm08szd4rqwy3r67
