apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-sbr-conf
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "macvlan-sbr",
    "plugins": [
      {
        "type": "macvlan",
        "master": "eno10.30",
        "mode": "bridge",
        "capabilities": { "ips": true },
        "ipam": {
          "type": "static",
          "routes": [
            { "dst": "192.168.30.0/24", "gw": "192.168.30.1" }
          ]
        }
      },
      {
        "capabilities": { "mac": true },
        "type": "tuning"
      },
      {
      "type": "tuning",
      "mtu": 1500,
      "sysctl": {
        "net.ipv4.conf.all.arp_notify": "1",
        "net.ipv4.conf.default.arp_notify": "1"
         }
      },
      {
        "type": "sbr"
      }
    ]
  }'
