apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: httpbin.org
  labels:
    istio.io/use-waypoint: egress-shared-waypoint
    istio.io/use-waypoint-namespace: istio-gateways
spec:
  hosts:
  - httpbin.org
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
