apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: calibre
spec:
  sourcePVC: calibre-web-config
  trigger:
    schedule: "0 * * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: calibre-volsync
    volumeSnapshotClassName: openebs-zfs
    cacheCapacity: 1Gi
    cacheStorageClassName: openebs-hostpath
    cacheAccessModes: ["ReadWriteOnce"]
    accessModes: ["ReadWriteOnce"]
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      hourly: 24
      daily: 7
      weekly: 5
