---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre
  namespace: media
spec:
  accessModes: ["ReadWriteOnce"]
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "calibre-bootstrap"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: "openebs-zfs-ssd"
