---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: isponsorblocktv
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      isponsorblocktv:
        replicas: 1
        strategy: RollingUpdate

        containers:
          app:
            image:
              repository: ghcr.io/dmunozv04/isponsorblocktv
              tag: v2.2.1
            env:
              TZ: ${TIMEZONE}

    persistence:
      config:
        enabled: true
        type: secret
        name: isponsorblocktv-secret
        globalMounts:
          - path: /app/data/config.json
            subPath: config.json
            readOnly: true
