apiVersion: v1
kind: Secret
metadata:
    name: isponsorblocktv-secret
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:5CgyRgwpXZmdJnUGWFkY7VY5kGMwUBQuS5WdOMq4RmPT9u1QYNRXRZochjoDhNGG+1fGIcRHOp49cLsfLFkIOgwld7A8GHb7bRhfyzItuEsL05+WL1olR+uy/mxhyzMwMbGhZFVmMcNE34huOrnDxJ6h1V+lfIo6oTAi/J9qZ6G9mXpJmaSPiwIO9uOVlm8Bi25k26jhHPpKcabq5PcbZLcJPupKCfv5GpDwVEFpNgkX9CnDjCVjjSAatxujbZWsWKjCgLLlEKImR2C/kPvKAy4b7yoFpTA/e5YoHfOv4gMrfStEHdjOG+Opsd0OaDpiwN3t58v2mEyq4wPMAItHNab7i1LooM4jgVse7Doh05OPyaGPHWNgDq+9JJmdu1Nvmad7vkt6iPv8VjVBuIW141irovPAC5FOzTZ1mbHCDGqexfEGPWSG1b5RjGch6JpQGFDt/Ct+noh85mK76Z8/MzhPvp+prc8jA4VJaS9tJW2rKz9hL+2zbEolrFFItXeOvNQJ9pi6GYEcIplv9hg5eAFQ4Q7WUtSj08xWZ0qpfYs/oRV2TOSVX2EQHbfoAFyqkvAvBDi8oBscj90VEVb//wPbd6LtrWm8PEzfLVJSN4jKRZkjBih/rDyS80hV4RdKuUgI72f3srNsZdGTLFlhGMXFjRD3rYfmnGbpE0vQkZUBciAHOYx7VxKhfjkKtLYVroJY2U8OTHKJY63QWmJH6d18d1nFbc+57tTErauA3tjnvYXAl7spzJFEqf9XYbqWbEcnVfhgb8aw3KFGAVux/uVixon2CB4ncUJlcBWEkeeCw1UWmxUVer0tBX1T7qKl6lRzNE7pPjfuK21YTZZgr7Je4Qp8CV79RkjLjh9g/iq5iLGQL2UJbRceu/9YIMd5GPPl6PJBzYahrppJPklIZkasYQCQ7hTsD85irF0lVvVmovyDcezPDF5eCEshieZM0XWpN92OlYWsciUsDD+eNDhDpht/cJCfg+0wY2bLQd3T843S4QdFptsqChG0VLRuFkOX,iv:jG/YE58q8VYqomBf9FoOhH3TLQR5n7B43DDciM+yqJo=,tag:E4k+yHj6nbuUQgJ/PYqD5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w8pq3mz7lhcnf3ajppkf9ee9j7ywapkenrads9nk3yjm08szd4rqwy3r67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQTdETG05U2RwMCtYWFZG
            eXcySnNVSE5UeG9SWXNkTlNmRVNtRU94dVFvCmZ4OGdoYU1ycStGRE5TVGU4SkNY
            K1JPS2d1dDlHY0hXSjZsek5USzE2Tm8KLS0tICs3WmNab1Y0bjhWOC90UFltTlRJ
            SHQxZmtXeGhadU1BeEF6UEVadHVGVjQK2JypgghHwuBDE29MhtKieSGK6hbShF7R
            LHacj+5hFXA1izqVUzs7gFQSjUgyfwUuUpWNKIWerTiKbuF4tJWJGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T04:13:43Z"
    mac: ENC[AES256_GCM,data:Ow/BDB6lbfYyASumIdPeeIVxoFmI0g56QEoU+Fhot/ddEbLDtmmDw0mf8YLJcdm0K43GYe40f7/tmvcBGgkoa3y3/5kThyGknbHbvihW87r1dCvTMBf7oH8hOR3MsnSMfPEmE/ghGqBfB5CZINPIj7ORhUanSePwj3+X67TYtQI=,iv:Ve+fHnLg9y9TGEvMvW/qyEnlPdI0WTERlBMoWLD4XMA=,tag:wkDH9+4ZSEBBYgpNAfNsnQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
