---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./prometheus-operator-crds/ks.yaml
  - ./namespace.yaml
#  - ./smartctl-exporter/ks.yaml
