---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vpngw
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3

  values:
    controllers:
      prowlarr:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [
                {
                  "name": "vpngw",
                  "namespace": "kube-system",
                  "ips": ["192.168.36.1/24", "2001:470:ee86:36:192:168:36:1/64"]
                }
              ]

        containers:
          app:
            image:
              repository: ghcr.io/bubuntux/nordlynx
              tag: 2025-06-01@sha256:a0b5742991a3556a2c340f79132ac2dcee1beea413508c86301d657e998924d2
            env:
              TZ: ${TIMEZONE}
              QUERY:
                valueFrom:
                  secretKeyRef:
                    name: vpngw-secret
                    key: query
              PRIVATE_KEY:
                valueFrom:
                  secretKeyRef:
                    name: vpngw-secret
                    key: private_key
            securityContext:
              privileged: true
              capabilities:
                add:
                - NET_ADMIN
    defaultPodOptions:
      nodeSelector:
        feature.node.kubernetes.io/network-interface.bond: "true"
    service:
      app:
        controller: vpngw
        enabled: false
