kind: ENC[AES256_GCM,data:7V2kiokw,iv:B/YFfzEsONy5/+ms59yi++kQd0stK3buQ7a/RxYxU+o=,tag:caP2w1hKiEZ7lZ2XZ/UoHA==,type:str]
ansible_user: ENC[AES256_GCM,data:m5DfnqLW,iv:fqwRjHqDchbDm2Tx4m0tZNgKmQCXh7kdUum7g121K2M=,tag:h+QQ7gR5kXhMydjGcRZgcg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:TM5cBTE92BzqJVIg,iv:Jdi2OEeOu6siuvKvYm9QZPrpXAkSRGpy0crezZUDNNE=,tag:azsKdwvSQsEhdP08baCIfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w8pq3mz7lhcnf3ajppkf9ee9j7ywapkenrads9nk3yjm08szd4rqwy3r67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2d0trMElCNlZWSThHZVFy
            aUhwUGVLWS8zMysrdG5KL2hoTzFQaHptYWwwClR4RTJrRy84TG9nWVBtNXhhT0hM
            Slc4eFJ0WHZKQlQvaXZCUTIwMnJ3R1EKLS0tIEpKUXNVZGh1YUZzY1J0T1YzL1Jj
            WndybHVtdDZoVzdCS1p4bnIvQ2N1MWsKJq6cIPFfVANK+vP80VeA0tJw8xFsQMat
            6bRzAQdBD4vdptEuXdVHe3gy4xUUdx9jiyaH/GsxFMzGkrGMtE1u2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-04T11:50:55Z"
    mac: ENC[AES256_GCM,data:lw/Va4L8kyhILC6YhpNqfbLG+MXJUoDKZyH0EeW5vbstuoknd7cLRATwK07z7NQZB+1dLw87BknLLdf6C4g0yOpUKohasVGetGfTjwh9sNhNqW+O8HEUG4LoR3F0fn6mSruEFrMcZGkQhl6F5Zk8Z5PwNa4xXK7b18yNzh0MazY=,iv:j20pJDvgrilzboC5rB6r1R8nIRp/MN4mFgZFkT74Z5E=,tag:EJSMKCg7jBCmyjPOTN1R3g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
