apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-minio
type: Opaque
stringData:
    #ENC[AES256_GCM,data:uqsHLieQvk4LhAcNFmxwgB95sw==,iv:BKfXGuG/nL2I4rI9mZrGAnPqMKTMfSK8+jZebgXAhxY=,tag:8yhZun+sCMzkN8ClhgyU3A==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:o23/8j8kOiPKz6eGg4EfRaJq36PZJ/YMj34M,iv:hoAJgFlnlutr4vmm8lkq+p/xcpx93PcoBtEyf5t/GnY=,tag:ymjhH5mrFWDp4OT46SRwpw==,type:str]
    #ENC[AES256_GCM,data:5LONeCTTuLd1/ntGsezcxT1mbChRtXjF/dZvByaF,iv:CSWdeRTY+nJYZSBYyXdSAO+BzeG4cadKxp7kmrYTd28=,tag:zUTHxbpZnUJis5FORXen6A==,type:comment]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:IQ0pLpAuubMyq1wY+pqe1bgc,iv:Y1E+20Utut3uJAxCVcKtSPjyuXd6g/1PGbPFuUSfqSY=,tag:X7vPNiZB0+7xvzdqIL3UlA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Ha31g1Mi4jtPvupLh6Yh15kT7XA=,iv:sDdVaFXPMU+n5oMfXc+vphsfdbVgVRY3tJEWKGskqIo=,tag:zY/erqZ0YsHcpicoff3FBQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:fw7gL43E0R6rq/MmQ7JlYwGxGvDGYLg4,iv:F0nl4g+T3umoKYmajiXHyumaF26ZFjWl23e4iO/58FM=,tag:voPvvTJmtmpBZFsh6KWgNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w8pq3mz7lhcnf3ajppkf9ee9j7ywapkenrads9nk3yjm08szd4rqwy3r67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVXprM1ptRGg3aVRnRzZp
            OE5McXFkQ2tOcWtvRlVBMEhZWms2cmhRQ0ZJCk1najEvOElTZE9oemwvc0RNRWFM
            UVgxcmtEMWJLRVJUQkViWnZoTWduN0UKLS0tIG9LS005REhQVlQ1cEk0Y3B1Mjdx
            c2ZXTEQ1VE1McUFEUC93Z1RSSlBwUlUKDRwwWpiwAxyxGnKqgPFtRVaGa1hmlU2b
            Rqavft/ELCeHk+w7iGzDLcAunZRYX25SJIXjArqNsQcWBDSupodMTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-28T02:48:45Z"
    mac: ENC[AES256_GCM,data:hi0sxVdxs5JrfKTLpv+a8pd9T/mVyI559EHMry9jpy3AcFzIr9zyGS/t/wvRaPyrqxjG3RZZugPuSExczhFv5zW4L1QsoLXRnHw8+FDdsefmWauI6uZEqIvZSmD5oe/6dRldqKPEibej6drkvzRrJqRBkGj3qj9M5JkRGe/K6m0=,iv:7LZ0OSlivtVwVKVKqs79m8vb9y4u5m1V5FX3lGc9NII=,tag:b9hryldHN4Q0Pht3wbf6cA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
