---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whereabouts
spec:
  interval: 30m
  chart:
    spec:
      chart: whereabouts-chart
      version: 0.9.0
      sourceRef:
        kind: HelmRepository
        name: k8snetworkplumbingwg
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    resources:
      requests:
        cpu: "10m"
        memory: "20Mi"
      limits:
        cpu: "100m"
        memory: "50Mi"
