apiVersion: v1
kind: Secret
metadata:
    name: wg-config
type: Opaque
stringData:
    wg0.conf: ENC[AES256_GCM,data:N86oHOyDAs/uPJnIZhOqvvk8FllQaG/Jdf5hIYAvo7eC0cATfd44enChbdXaKj9w3lThV4j3bO5fZauBBQiiRxy+rBPSDNqB2J50/eOyFKo4MLsyWqgWbj9V3IWVDUngvbfRXtLFjbnfHD+oPwTEwNniutlwC4ZhSzMkviJtAOGopbabqVCrjHmjqkp7CnsyB5+w/1aiPvxsuuFvxqKN5YOz3J714K6U0PobPdhBElt7AMb8DN1/zIYeCviVQPKDc5APuIDJa0YsEmea7CAsXWsTVAdLXAEbteFBVidkS/KrwzjtOAUlLUdSm3jYdfiQjL+etY6JNJ+DqeVjY+89Ds/Dc+nxoHj450jgxFnJZo4bGZqEy/T7Oc6XRiAJJLsCRiAXGlhP80kbJ7cP7jzkJxyuH96yuH0k,iv:ttQ8gqjyc2Y6C9DpnyUnjeiFPmcFKMvW1edxrGgKsvM=,tag:zzdYpAoImjGOmwCsP7EYjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w8pq3mz7lhcnf3ajppkf9ee9j7ywapkenrads9nk3yjm08szd4rqwy3r67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VitYa3VRY1UyV3RpMThF
            dWJVUTNEOHB0V0hXVEJHcEVMazhlbkhYVGdZClcrSzdVYmxQd3VDdDBmVFRMRzBk
            TWlPa2xObWNDWmZKem1HaHIySmtLUXMKLS0tIHhlQWtCKzNCaUFFLzFkZGo4SElv
            SzQxaExxT2FGUlE0R1FKcEpwZG5oaTgKhe9IHqT7a0loQ/chWor2CkV7Hn9XKzpG
            5xwS3knmIdoccwwrPJY9VMg0BYebDqIq4qE9En9bT19ez8UHPM24hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-16T01:46:10Z"
    mac: ENC[AES256_GCM,data:N2ijp6nrTP9G8X/LWFFQvljSP5K1hHifuWidNf934rS0N4THY2WwV0aqgVzJA5jUhXzeAD/eq9yZqwJ4zOs55+h+FbB06gDnU+KnBJwafdX1j1py7V7eTw4vWxnTHXfAewUA85O1dSuVB8QEkxEgEnyQH/WlBacEHcepUntqVBk=,iv:P448PLV9gEhykp6yQcsIgUNAGh8TWPw5fAtPVQGPXqc=,tag:HnDuUo+VrTyxWdqhUPbI3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
