---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: ${job}
  namespace: ${ns}
spec:
  trigger:
    manual: restore-once
  restic:
    repository: ${app}-volsync-minio
    destinationPVC: ${claim}
    copyMethod: Direct
    previous: ${previous}
    moverSecurityContext:
      runAsUser: ${puid}
      runAsGroup: ${pgid}
      fsGroup: ${pgid}
