---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k8snetworkplumbingwg
  namespace: flux-system
spec:
  type: oci
  interval: 5m
  url: oci://ghcr.io/k8snetworkplumbingwg
