---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  - pvc
  # Flux-Kustomizations
  - ./calibre-web/ks.yaml
  - ./filebrowser/ks.yaml
  - ./isponsorblocktv/ks.yaml
#  - ./photoprism/ks.yaml
  - ./plex/ks.yaml
