---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  #- istio-base/ks.yaml
  #- istiod/ks.yaml
  #- istio-cni/ks.yaml
  #- istio-ztunnel/ks.yaml
