---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actions-runner-controller.yaml
  - ./backube.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./calico.yaml
  - ./coredns.yaml
  - ./external-dns.yaml
  - ./goldpinger.yaml
  - ./grafana.yaml
  - ./istio.yaml
  - ./jetstack.yaml
  - ./kiali.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  - ./metallb.yaml
  - ./metrics-server.yaml
  - ./openebs.yaml
  - ./piraeus.yaml
  - ./prometheus-community.yaml
  - ./spegel.yaml
  - ./stakater.yaml
