apiVersion: v1
kind: Secret
metadata:
    name: gluvpngw-secret
type: Opaque
stringData:
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:K3EuFR33whOiGXx+4g==,iv:ey2Z0Bmk3buZR2cyk6kYMkYuNJI+oE3XKE9a4VrNQrg=,tag:Nnv4pgRX45rQcVqJsSn2Uw==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:u0f+oWEVDqRSrY93sq5rIMZh384S0BfN7C8tj1Sw7omawgOdV4qMBjbbFmA=,iv:Uwt59hFD/3Ny00d5SNELIh0MDEtGkth6cXhWONvMNds=,tag:0LXfSBdzuhp8s0Lew8r6Rw==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:iCdf1/e+dmTY/y+REKqKPaoqESijqkCj1Q1+4A+qr5zT4sRxrDP0Sd3WsUQ=,iv:b6M5ZFfWfh6CAg6kQVOgacaYoPkUKcEPCePe9DzXYn0=,tag:mGneTuCm3YA/VNy1JmYrag==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:IE6VOAUcDL8NkiQ=,iv:c+6ZwQpsp12UQBv0ChScA/MVe0r7QAAG+BhCG++ohrs=,tag:svnYqvdGAtRbpPRWhSJ8mg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w8pq3mz7lhcnf3ajppkf9ee9j7ywapkenrads9nk3yjm08szd4rqwy3r67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQTdETG05U2RwMCtYWFZG
            eXcySnNVSE5UeG9SWXNkTlNmRVNtRU94dVFvCmZ4OGdoYU1ycStGRE5TVGU4SkNY
            K1JPS2d1dDlHY0hXSjZsek5USzE2Tm8KLS0tICs3WmNab1Y0bjhWOC90UFltTlRJ
            SHQxZmtXeGhadU1BeEF6UEVadHVGVjQK2JypgghHwuBDE29MhtKieSGK6hbShF7R
            LHacj+5hFXA1izqVUzs7gFQSjUgyfwUuUpWNKIWerTiKbuF4tJWJGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-02T02:56:04Z"
    mac: ENC[AES256_GCM,data:/uI/K0l6xuV8R2I1k4bHzIfxPAFI/qwHI+qBBw/MmsutTnz9NOkTEWe4JHlogUbCBRlALelfKIEjwFrO14bswR5HoHeRiUp1L2gA5nvdvID2c3owfNQy5BVMlQzdcs7IsTBM5/yRXeZjZFLJFHYe9NqVHl4BjozxDmqEzQyFxM8=,iv:5Qa0i3Cq7cgKv3zSZx9DVCMDI1FK3ddBE2UgIvj7epw=,tag:2/ekBWqtrk+TcBAoyt3Rvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
