---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: abasitt-tech
spec:
  secretName: abasitt-tech-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: abasitt.tech
  dnsNames:
    - abasitt.tech
    - "*.abasitt.tech"
    - "*.neo.abasitt.tech"
