---
- name: Kubeconfig
  block:
    - name: Kubeconfig | Copy kubeconfig to the project directory
      when: k3s_primary_control_node
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ repository_base }}/kubernetes/router/kubeconfig"
        flat: true

    - name: Kubeconfig | Update kubeconfig with the correct load balancer address
      delegate_to: localhost
      become: false
      run_once: true
      ansible.builtin.replace:
        path: "{{ repository_base }}/kubernetes/router/kubeconfig"
        regexp: '((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)'
        replace: "{{ kubeapi_addr }}"

    - name: Kubeconfig | Update kubeconfig with the correct context
      delegate_to: localhost
      become: false
      run_once: true
      ansible.builtin.replace:
        path: "{{ repository_base }}/kubernetes/router/kubeconfig"
        regexp: default
        replace: router
