---
- name: Kubeovn
  block:
    - name: Kubeovn | Check if kubeovn HelmChart exists
      kubernetes.core.k8s_info:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        name: kubeovn
        kind: HelmChart
        namespace: kube-system
      register: kubeovn_helmchart

    - name: Kubeovn | Wait for kubeovn to rollout
      when: kubeovn_helmchart.resources | count > 0
      kubernetes.core.k8s_info:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        name: helm-install-kubeovn
        kind: Job
        namespace: kube-system
        wait: true
        wait_condition:
          type: Complete
          status: true
        wait_timeout: 360

    - name: Kubeovn | Patch the kubeovn HelmChart to unmanage it
      when: kubeovn_helmchart.resources | count > 0
      kubernetes.core.k8s_json_patch:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        name: kubeovn
        kind: HelmChart
        namespace: kube-system
        patch:
          - op: add
            path: /metadata/annotations/helmcharts.helm.cattle.io~1unmanaged
            value: "true"

    - name: Kubeovn | Delete the kubeovn HelmChart CR
      when: kubeovn_helmchart.resources | count > 0
      kubernetes.core.k8s:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        name: kubeovn
        kind: HelmChart
        namespace: kube-system
        state: absent

    # Ref: https://github.com/k3s-io/helm-controller/issues/33
    - name: Kubeovn | Force delete the kubeovn HelmChart
      when: kubeovn_helmchart.resources | count > 0
      kubernetes.core.k8s:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        name: kubeovn
        kind: HelmChart
        namespace: kube-system
        state: patched
        definition:
          metadata:
            finalizers: []
