---
- name: Kubeconfig
  block:
    - name: Kubeconfig | Copy kubeconfig to the project directory
      when: k3s_primary_control_node
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ repository_base }}/kubernetes/router/kubeconfig"
        flat: true

    - name: Kubeconfig | Update kubeconfig with the correct load balancer address
      delegate_to: localhost
      become: false
      run_once: true
      ansible.builtin.replace:
        path: "{{ repository_base }}/kubernetes/router/kubeconfig"
        regexp: https://127.0.0.1:6443
        replace: "https://{{ kubeapi_addr }}:6443"

    - name: Kubeconfig | Update kubeconfig with the correct context
      delegate_to: localhost
      become: false
      run_once: true
      ansible.builtin.replace:
        path: "{{ repository_base }}/kubernetes/router/kubeconfig"
        regexp: default
        replace: router
