---
# https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/
# https://github.com/PyratLabs/ansible-role-k3s

k3s_control_node: true
k3s_server:
  node-ip: "{{ ansible_host }},{{ ansible_default_ipv6.address }}"
  tls-san:
    - "{{ kubeapi_addr }}"
  docker: false
  flannel-backend: "host-gw"             # This needs to be in quotes
  disable:
    - coredns
#    - flannel                         # Disable flannel
    - local-storage                   # Disable local-path-provisioner  - installed with Flux
    - metrics-server                  # Disable metrics-server          - installed with Flux
    - servicelb                       # Disable servicelb               - replaced with metallb and installed with Flux
    - traefik                         # Disable traefik                 - replaced with ingress-nginx and installed with Flux
  disable-network-policy: true
  disable-cloud-controller: true
  disable-kube-proxy: false
  write-kubeconfig-mode: "644"
  secrets-encryption: true
  cluster-cidr: "{{ cluster_cidr }},{{ cluster_v6cidr }}"
  service-cidr: "{{ service_cidr }},{{ service_v6cidr }}"
  kubelet-arg:
    #- "node-status-update-frequency=4s"
    - "image-gc-high-threshold=55"
    - "image-gc-low-threshold=50"
  kube-controller-manager-arg:
    - "bind-address=0.0.0.0"          # Required to monitor kube-controller-manager with kube-prometheus-stack
  kube-scheduler-arg:
    - "bind-address=0.0.0.0"          # Required to monitor kube-scheduler with kube-prometheus-stack
  etcd-expose-metrics: true           # Required to monitor etcd with kube-prometheus-stack
  etcd-disable-snapshots: true
  kube-apiserver-arg:
    - "default-not-ready-toleration-seconds=20"
    - "default-unreachable-toleration-seconds=20"
