---
# https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/
# https://github.com/PyratLabs/ansible-role-k3s

k3s_control_node: true
k3s_server:
  node-ip: "{{ ansible_host }},{{ ansible_v6host }}"
  tls-san:
    - "{{ kubeapi_addr }}"
  flannel-backend: "host-gw"
  disable: ["coredns", "local-storage", "metrics-server", "servicelb", "traefik"]
  docker: false
  disable-network-policy: true
  disable-cloud-controller: true
  disable-helm-controller: false
  disable-kube-proxy: false
  cluster-cidr: "{{ cluster_cidr }},{{ cluster_v6cidr }}"
  service-cidr: "{{ service_cidr }},{{ service_v6cidr }}"
  kubelet-arg:
    - "image-gc-high-threshold=55"
    - "image-gc-low-threshold=50"
    - "node-ip={{ ansible_host }}" #this must stay else changing route on a router changes nodeip to publicip
  kube-controller-manager-arg:
    - "bind-address=0.0.0.0"
  kube-scheduler-arg:
    - "bind-address=0.0.0.0"
  kube-apiserver-arg:
    - "default-not-ready-toleration-seconds=20"
    - "default-unreachable-toleration-seconds=20"
  pause-image: registry.k8s.io/pause:3.10
  secrets-encryption: true
  write-kubeconfig-mode: "644"