---
apiVersion: frrk8s.metallb.io/v1beta1
kind: FRRConfiguration
metadata:
 name: neo-bgp-peers
 namespace: default
spec:
 bgp:
   routers:
   - asn: 65002
     neighbors:
     - address: 192.168.30.41
       sourceaddress: 192.168.30.2
       asn: 64512
       toAdvertise:
         allowed:
           prefixes:
           - 10.40.0.0/16
           - 10.96.0.0/16
       toReceive:
         allowed:
           mode: all
     - address: 192.168.30.42
       sourceaddress: 192.168.30.2
       asn: 64512
       toAdvertise:
         allowed:
           prefixes:
           - 10.40.0.0/16
           - 10.96.0.0/16
       toReceive:
         allowed:
           mode: all
     - address: 192.168.30.43
       sourceaddress: 192.168.30.2
       asn: 64512
       toAdvertise:
         allowed:
           prefixes:
           - 10.40.0.0/16
           - 10.96.0.0/16
       toReceive:
         allowed:
           mode: all
     prefixes:
     - 10.40.0.0/16
     - 10.96.0.0/16