autoscaling:
  minReplicas: 1
  maxReplicas: 1
service:
  type: ClusterIP
  ipFamilyPolicy: RequireDualStack
  ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    - name: hbone
      port: 15008
      protocol: TCP
      targetPort: 15008
resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

volumes:
  - emptyDir: {}
    name: workload-socket
  - name: egressgateway-certs
    secret:
      optional: true
      secretName: istio-egressgateway-certs
  - name: egressgateway-ca-certs
    secret:
      optional: true
      secretName: istio-egressgateway-ca-certs

volumeMounts:
  - mountPath: /var/run/secrets/workload-spiffe-uds
    name: workload-socket
  - mountPath: /etc/istio/egressgateway-certs
    name: egressgateway-certs
    readOnly: true
  - mountPath: /etc/istio/egressgateway-ca-certs
    name: egressgateway-ca-certs
    readOnly: true
