autoscaling:
  minReplicas: 1
  maxReplicas: 1

podAnnotations:
  #prometheus.io/port: "15020"
  #prometheus.io/scrape: "true"
  #prometheus.io/path: "/stats/prometheus"
  #inject.istio.io/templates: "gateway"
  #sidecar.istio.io/inject: "true"
  k8s.v1.cni.cncf.io/networks: |
      [
        {
          "name": "multus-egress",
          "ips": ["192.168.30.71/24", "2001:470:ee86:30:192:168:30:71/64"]
        }
      ]

service:
  type: ClusterIP
  ipFamilyPolicy: RequireDualStack
  ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: mesh
      appProtocol: hbone
      port: 15008
      protocol: TCP
      targetPort: 15008
resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

nodeSelector:
  kubernetes.io/hostname: neotc1bm-w2
