autoscaling:
  minReplicas: 1
  maxReplicas: 1
service:
  type: ClusterIP
  ipFamilyPolicy: RequireDualStack
  ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    - name: hbone
      port: 15008
      protocol: TCP
      targetPort: 15008
resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
volumes:
  - configMap:
      defaultMode: 420
      name: istio-ca-root-cert
    name: istiod-ca-cert
volumeMounts:
  - mountPath: /var/run/secrets/workload-spiffe-uds
    name: workload-socket
  - mountPath: /var/run/secrets/istio
    name: istiod-ca-cert
