autoscaling:
  minReplicas: 1
  maxReplicas: 1

service:
  type: ClusterIP
  ipFamilyPolicy: RequireDualStack
  ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: mesh
      appProtocol: hbone
      port: 15008
      protocol: TCP
      targetPort: 15008
resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

nodeSelector:
  kubernetes.io/hostname: neotc1bm-w2
