---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-egressgateway
spec:
  interval: 5m
  chart:
    spec:
      chart: gateway
      version: 1.24.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 10m
  install:
    timeout: 10m
    replace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
      strategy: rollback
    cleanupOnFail: true
    crds: CreateReplace
  test:
    enable: true
  rollback:
    recreate: true
    force: true
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  maxHistory: 3
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: istio-egressgateway
              namespace: istio-gateways
            patch: |
              - op: add
                path: /spec/template/spec/containers/0/args
                value:
                  - proxy
                  - waypoint
                  - --domain
                  - $(POD_NAMESPACE).svc.cluster.local
                  - --proxyLogLevel=warning
                  - --proxyComponentLogLevel=misc:error
                  - --log_output_level=default:info
  valuesFrom:
    - kind: ConfigMap
      name: istioegressgw-helm-values
