---
crds:
  enabled: true
prometheus:
  namespace: observability
  serviceAccount: kube-prometheus-stack-prometheus
  serviceMonitor:
    enabled: true
  prometheusRule:
    enabled: true
frrk8s:
  enabled: true