---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs-collector
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-logs-collector
  interval: 1h
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: victoria-logs-collector
    podMonitor:
      enabled: false
    remoteWrite:
      - url: https://vlogs.neo.basitlab.com
        maxDiskUsagePerURL: 1GB
    collector:
      extraFields: '{"cluster":"router"}'
      streamFields:
        - cluster
        - kubernetes.pod_name
        - kubernetes.pod_namespace
        - kubernetes.container_name
        - kubernetes.pod_labels.app.kubernetes.io/name
    extraArgs:
      enableTCP6: true
      kubernetesCollector.decolorizeFields: _msg
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 256Mi
