---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: squid-vpn
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      squid-vpn:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [
                {
                  "name": "downloads",
                  "namespace": "kube-system",
                  "ips": ["192.168.36.16/23", "2001:470:ee86:36:192:168:36:16/64"],
                  "default-route": ["192.168.36.1", "2001:470:ee86:36:192:168:36:1"]
                }
              ]

        initContainers:
          fixroutes:
            image:
              repository: alpine
              tag: 3.22.1
            env:
            - name: DEV
              value: eth0
            command:
            - '/bin/sh'
            - '-c'
            - |
              # Add static IPv4 route
              ip route add 10.0.0.0/8 via 169.254.1.1 dev $DEV
              ip route add 192.168.0.0/16 via 169.254.1.1 dev $DEV

              # Add static IPv6 route
              ip -6 route add 2001:470:ee86::/48 via fe80::ecee:eeff:feee:eeee dev $DEV
            securityContext:
              capabilities:
                add:
                - NET_ADMIN

        containers:
          app:
            image:
              repository: ubuntu/squid
              tag: 6.10-24.10_beta
            ports:
              - containerPort: &port 3128
                name: squid
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 3128
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 3128
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsUser: 65534
              runAsGroup: 65534
              fsGroupChangePolicy: OnRootMismatch
              supplementalGroups: [44, 10000]
              capabilities:
                add: ["NET_BIND_SERVICE"]
              seccompProfile:
                type: RuntimeDefault
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
    defaultPodOptions:
      nodeSelector:
        feature.node.kubernetes.io/network-interface.bond: "true"
    persistence:
      logs:
        enabled: true
        type: emptyDir
        sizeLimit: 1Gi
        globalMounts:
          - path: /var/log/squid
      cache:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: openebs-zfs-ssd
        globalMounts:
          - path: /var/spool/squid
      config:
        enabled: true
        type: secret
        name: squid-vpn-config
        globalMounts:
          - path: /etc/squid/squid.conf
            subPath: squid.conf
    service:
      app:
        controller: squid-vpn
        type: LoadBalancer
        loadBalancerClass: metallb
        ipFamilyPolicy: PreferDualStack
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${METALLB_SQUIDVPN_V6ADDR},${METALLB_SQUIDVPN_V4ADDR}
        externalTrafficPolicy: "Local"
        allocateLoadBalancerNodePorts: false
        ports:
          http:
            port: *port
