---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istiod
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  path: "./kubernetes/apps/networking/istiod/app"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
  dependsOn:
    - name: istio-base
      namespace: flux-system
