---
apiVersion: crd.projectcalico.org/v1
kind: BGPConfiguration
metadata:
  name: default
spec:
  asNumber: 64512
  nodeToNodeMeshEnabled: true
  serviceClusterIPs: []
  serviceLoadBalancerIPs:
    - cidr: "${METALLB_L3_V4RANGE}"
    - cidr: "${METALLB_L3_V6RANGE}"
