#---
#apiVersion: crd.projectcalico.org/v1
#kind: BGPFilter
#metadata:
#  name: drop-pod-network
#spec:
#  exportV4:
#    - action: Reject
#      matchOperator: In
#      cidr: ${CLUSTER_CIDR}
#  exportV6:
#    - action: Reject
#      matchOperator: In
#      cidr: ${CLUSTER_V6CIDR}
---
apiVersion: crd.projectcalico.org/v1
kind: BGPPeer
metadata:
  name: ipv4-gw-k8srouter
spec:
  peerIP: 192.168.30.2
  asNumber: 65002
  keepOriginalNextHop: true
#  filters:
#    - drop-pod-network
#---
#apiVersion: crd.projectcalico.org/v1
#kind: BGPPeer
#metadata:
#  name: ipv6-gw-k8srouter
#spec:
#  peerIP: 2001:470:ee86:30::1
#  asNumber: 65001
#  keepOriginalNextHop: true
#  filters:
#    - drop-pod-network
