---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bgpconfiguration.yaml
  - ./bgpgatewaypeer-k8srouter.yaml
  - ./bgpgatewaypeer.yaml
