---
- name: Label and Taint Node
  block:
    - name: Label baremetal nodes
      kubernetes.core.k8s:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        api_version: v1
        kind: Node
        name: "{{ item }}"
        state: present
        definition:
          metadata:
            labels:
              node.kubernetes.io/infrastructure-type: baremetal
              node.kubernetes.io/storage-type: zfs
      loop:
        - neobl1bm-m3
        - neotc1bm-w2
    - name: Label VM nodes
      kubernetes.core.k8s:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        api_version: v1
        kind: Node
        name: "{{ item }}"
        state: present
        definition:
          metadata:
            labels:
              node.kubernetes.io/infrastructure-type: vm
      loop:
        - neohv1vm-m1
        - neohv2vm-m2
    - name: Label and taint laptop node
      kubernetes.core.k8s:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        api_version: v1
        kind: Node
        name: neoas1lm-w1
        state: present
        definition:
          metadata:
            labels:
              node.kubernetes.io/infrastructure-type: laptop
          spec:
            taints:
              - key: node-role.kubernetes.io/laptop
                value: "true"
                effect: NoSchedule
