---
# https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/
# https://github.com/PyratLabs/ansible-role-k3s

k3s_control_node: true
k3s_server:
  #node-ip: "{{ ansible_host }},{{ ansible_default_ipv6.address }}"
  node-ip: "{{ ansible_v6host }},{{ ansible_host }}"
  tls-san:
    - "{{ kubeapi_addr }}"
    - "{{ ansible_v6host }}"
  docker: false
  flannel-backend: "none"             # This needs to be in quotes
  disable:
    - coredns
    - flannel                         # Disable flannel                 - replaced with calico
    - local-storage                   # Disable local-path-provisioner  - installed with Flux
    - metrics-server                  # Disable metrics-server          - installed with Flux
    - servicelb                       # Disable servicelb               - replaced with metallb and installed with Flux
    - traefik                         # Disable traefik                 - replaced with ingress-nginx and installed with Flux
  disable-network-policy: true
  disable-cloud-controller: true
  disable-kube-proxy: false            # calico eBPF mode
  pause-image: registry.k8s.io/pause:3.10
  secrets-encryption: true
  cluster-cidr: "{{ cluster_v6cidr }},{{ cluster_cidr }}"
  service-cidr: "{{ service_v6cidr }},{{ service_cidr }}"
  etcd-expose-metrics: true           # Required to monitor etcd with kube-prometheus-stack
  etcd-disable-snapshots: true
  kubelet-arg:
    #- "node-status-update-frequency=4s"
    - "image-gc-high-threshold=55"
    - "image-gc-low-threshold=50"
    - "node-ip={{ ansible_v6host }}"
  kube-controller-manager-arg:
    - "bind-address=::"          # Required to monitor kube-controller-manager with kube-prometheus-stack
    # https://github.com/k3s-io/k3s/issues/1264
    - "node-monitor-period=4s"
    - "node-monitor-grace-period=16s"
  kube-scheduler-arg:
    - "bind-address=::"          # Required to monitor kube-scheduler with kube-prometheus-stack
  kube-apiserver-arg:
    - "bind-address=::"
    #- "--advertise-address={{ kubeapi_addr }}"
    - "anonymous-auth=true"           # Required for HAProxy health-checks
    - "default-not-ready-toleration-seconds=20"
    - "default-unreachable-toleration-seconds=20"
  write-kubeconfig-mode: "644"
