---
hub: gcr.io/istio-release
variant: "distroless"
multiCluster:
  clusterName: ${CLUSTER_NAME}
meshConfig:
  defaultConfig:
    proxyMetadata:
      ISTIO_META_DNS_CAPTURE: "true"
  # reducing for home-usage
  resources:
    requests:
      cpu: 100m
      # Ztunnel memory scales with the size of the cluster and traffic load
      # While there are many factors, this is enough for ~200k pod cluster or 100k concurrently open connections.
      memory: 128Mi
