---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-istio-base
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  path: "./kubernetes/apps/networking/istio/istio-base/app"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
