---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: squid-vpn
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      squid-vpn:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ubuntu/squid
              tag: 6.10-24.10_beta
            ports:
              - containerPort: &port 3128
                name: squid
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
              seccompProfile:
                type: RuntimeDefault
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile: { type: RuntimeDefault }
    persistence:
      cache:
        type: emptyDir
        globalMounts:
          - path: /var/spool/squid
      config:
        enabled: true
        type: configMap
        name: squid-vpn-config
        globalMounts:
          - path: /etc/squid/squid.conf
            subPath: squid.conf
            readOnly: true
    service:
      app:
        controller: squid-vpn
        type: LoadBalancer
        loadBalancerClass: metallb
        ipFamilyPolicy: PreferDualStack
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${METALLB_SQUIDVPN_V6ADDR},${METALLB_SQUIDVPN_V4ADDR}
        externalTrafficPolicy: "Local"
        allocateLoadBalancerNodePorts: false
        ports:
          http:
            port: *port
