---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./alertmanager-secrets.secret.sops.yaml
  - ./httproutes.yaml
configMapGenerator:
  - name: alertmanager-config-tpl
    files:
      - alertmanager.yaml=./alertmanager.yaml
generatorOptions:
  disableNameSuffixHash: true
