---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kea-dhcp
spec:
  interval: 5m
  chart:
    spec:
      chart: kea-dhcp
      version: 0.7.1
      sourceRef:
        kind: HelmRepository
        name: kea-dhcp
        namespace: flux-system
      interval: 10m
  install:
    timeout: 10m
    replace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: keadhcp-helm-values
