---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kea-dhcp
spec:
  interval: 5m
  chart:
    spec:
      chart: kea-dhcp
      version: 0.7.1
      sourceRef:
        kind: HelmRepository
        name: kea-dhcp
        namespace: flux-system
      interval: 10m
  install:
    timeout: 10m
    replace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: StatefulSet
              name: kea-dhcp
              namespace: default
            patch: |
              - op: add
                path: /spec/template/spec/hostNetwork
                value: true
              - op: replace
                path: /spec/template/spec/initContainers/0/command
                value:
                  - sh
                  - "-c"
                  - |
                    set -ex
                    cp /mnt/config-map/* /mnt/kea/
                    #manually add interfaces here, won't pick up from helmvalues
                    interfaces=br0,vlan40
                    echo "Selected interface $interfaces"
                    interfaces_json=$(echo $interfaces | sed 's/,/","/g' | sed 's/^/"/' | sed 's/$/"/')
                    echo "Interfaces JSON: $interfaces_json"
                    # Replace INTERFACE placeholder with JSON array of interfaces
                    sed -i "s/\"INTERFACE\"/${interfaces_json}/g" /mnt/kea/kea-dhcp4.conf
                    sed -i "s/\"INTERFACE\"/${interfaces_json}/g" /mnt/kea/kea-dhcp6.conf
                    sed -i "s/HOSTNAME/${HOSTNAME}/g" /mnt/kea/ha-init.json || true
                    touch /mnt/kea/ha.json
  valuesFrom:
    - kind: ConfigMap
      name: keadhcp-helm-values
