---
- name: Cluster Node labels
  hosts: master
  serial: 1
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2
  tasks:
    - name: Ensure Kubernetes is running
      ansible.builtin.include_role:
        name: xanmanning.k3s
        public: true
      vars:
        k3s_state: started

    - name: Apply node labels
      when: k3s_primary_control_node
      ansible.builtin.include_tasks: tasks/node_labels.yaml
