---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goldpinger
spec:
  interval: 30m
  chart:
    spec:
      chart: goldpinger
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: goldpinger
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    tolerations:
      - operator: Exists
        effect: NoSchedule
    extraEnv:
      IP_VERSIONS: 6
    service:
      type: ClusterIP
      port: 80
      ipFamilyPolicy: PreferDualStack
    resources:
      requests:
        cpu: 15m
        memory: 64M
      limits:
        cpu: 15m
        memory: 64M
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
