---
- name: Calico
  block:
    - name: Calico | Check if Calico HelmChart exists
      kubernetes.core.k8s_info:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        name: calico
        kind: HelmChart
        namespace: tigera-operator
      register: calico_helmchart

    - name: Calico | Wait for Calico to rollout
      when: calico_helmchart.resources | count > 0
      kubernetes.core.k8s_info:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        name: helm-install-calico
        kind: Job
        namespace: tigera-operator
        wait: true
        wait_condition:
          type: Complete
          status: true
        wait_timeout: 360

    - name: Calico | Patch the Calico HelmChart to unmanage it
      when: calico_helmchart.resources | count > 0
      kubernetes.core.k8s_json_patch:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        name: calico
        kind: HelmChart
        namespace: tigera-operator
        patch:
          - op: add
            path: /metadata/annotations/helmcharts.helm.cattle.io~1unmanaged
            value: "true"

    - name: Calico | Delete the Calico HelmChart CR
      when: calico_helmchart.resources | count > 0
      kubernetes.core.k8s:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        name: calico
        kind: HelmChart
        namespace: tigera-operator
        state: absent

    # Ref: https://github.com/k3s-io/helm-controller/issues/33
    - name: Calico | Force delete the Calico HelmChart
      when: calico_helmchart.resources | count > 0
      kubernetes.core.k8s:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        name: calico
        kind: HelmChart
        namespace: tigera-operator
        state: patched
        definition:
          metadata:
            finalizers: []
