apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    labels:
        cnpg.io/reload: "true"
stringData:
    username: ENC[AES256_GCM,data:YXpelkRlRks=,iv:BcPuEvze2VvIFvNWEsrjPLfaTzHiPmZMtMvp4Mb9Ovo=,tag:qy7Gmk1pvLoTmrdan1KD4Q==,type:str]
    password: ENC[AES256_GCM,data:MUXRpqZb+61jRiRo7h9pr51rk2w=,iv:oyHpnqH1NKpJ2Ll38Bb8cnRMbIu44EquRUVQnkE8Aqw=,tag:aVNCrYJ6auE7OZgm5tUxtA==,type:str]
    aws-access-key-id: ENC[AES256_GCM,data:Dgsg6c9NBmnJBrrZln/W0xDac5M=,iv:N7HxmAe40lNdfU8QO+V3XeJmteNx/wss0WLkhJc3Bq0=,tag:6go4gu68pamhLetyBPe5vw==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:dCJvkfbvRopzoqgmhZURukOoa3sMFbiV,iv:BP+NtgcvSDP+PYsogJk9l4TiBbHdD/jbpQdXbcxKK0Q=,tag:d3kFlgWb0S0EusZ2ODI6Iw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w8pq3mz7lhcnf3ajppkf9ee9j7ywapkenrads9nk3yjm08szd4rqwy3r67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQTdETG05U2RwMCtYWFZG
            eXcySnNVSE5UeG9SWXNkTlNmRVNtRU94dVFvCmZ4OGdoYU1ycStGRE5TVGU4SkNY
            K1JPS2d1dDlHY0hXSjZsek5USzE2Tm8KLS0tICs3WmNab1Y0bjhWOC90UFltTlRJ
            SHQxZmtXeGhadU1BeEF6UEVadHVGVjQK2JypgghHwuBDE29MhtKieSGK6hbShF7R
            LHacj+5hFXA1izqVUzs7gFQSjUgyfwUuUpWNKIWerTiKbuF4tJWJGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-08T10:24:42Z"
    mac: ENC[AES256_GCM,data:3GMsF4PQ/BFvcUkO4rwYq2dmFuPqUvBMdhgpw3m4OPXk+0jcT9c4IuBU0B7Y0QaEzwuOazAv4LAnaKDA2ePwg/jfNuYw0+MkurmLbwp5OEfJDQL78L8Wl1pb9KeI9fUDTRNDgfPbWdcFcgIw4XLeQTXyGpuHUH/8KzbP1JVIQsU=,iv:fv+4Tgtk6dM8XiaKHrrHA/H9w38S72fCgXCfCnrdf70=,tag:c5QgmYsgclWb8CK6ZrPieg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
