apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: downloads
  namespace: downloads
spec:
  config: |-
    {
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eno10.30",
      "mode": "bridge",
      "ipam": {
        "type": "static"
      }
    }
