---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-egress
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-egress",
      "plugins": [
        {
          "type": "macvlan",
          "master": "bond0.30",
          "mode": "bridge",
          "capabilities": {
            "ips": true
          },
          "ipam": {
            "type": "static"
          }
        },
        {
          "name": "egresssbr",
          "type": "sbr"
        }
      ]
    }
