#just the example nad
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vpngw
spec:
  config: |-
    '{
      "cniVersion": "0.3.0",
      "plugins": [
        {
          "type": "macvlan",
          "master": "eno10.30",
          "mode": "bridge",
          "ipam": {
            "type": "static",
          }
        },
        {
          "type": "tuning",
          "sysctl": {
            "net.ipv4.ip_forward": "1",
            "net.ipv6.conf.all.forwarding": "1"
          }
        }
      ]
    }'
