---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-egress
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-egress",
      "plugins": [
        {
          "type": "macvlan",
          "master": "eno10.30",
          "mode": "bridge",
          "capabilities": {
            "ips": true
          },
          "ipam": {
            "type": "static"
          }
        },
        {
        "type" : "route-override",
        "flushgateway" : true,
        "addroutes": [
        {
          "dst": "${SERVICE_CIDR}",
          "gw": "169.254.1.1"
        },
        {
          "dst": "0.0.0.0",
          "gw": "192.168.30.1"
        },
        {
          "dst": "${SERVICE_V6CIDR}",
          "gw": "fe80::ecee:eeff:feee:eeee"
        },
        {
          "dst": "::/0",
          "gw": "2001:470:ee86:30::1"
        }
        ]
      }
      ]
    }
