apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
        {
          "name": "curl-test",
          "ips": ["192.168.30.241/24"],
          "default-route": ["192.168.30.1"]
        }
      ]
spec:
  nodeSelector:
    kubernetes.io/hostname: neotc2bm-m2
  initContainers:
  - name: fixroutes
    image: alpine:3.21.3
    imagePullPolicy: IfNotPresent
    env:
    - name: DEV
      value: eth0
    command:
    - '/bin/sh'
    - '-c'
    - |
      ip route add 10.45.0.0/16 via $( ip route | grep "$DEV" | tr -s " " | cut -d " " -f 1 ) dev $DEV
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
  containers:
  - name: curl-container
    image: quay.io/curl/curl:8.12.1
    command: ["/bin/sleep", "infinity"]
