---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: busybox
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      busybox:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: docker.io/library/busybox
              tag: latest
    service:
      app:
        controller: busybox
        enabled: false
    command:
      - sh
      - "while true; do ping localhost; sleep 60; done"
    nodeSelector:
      kubernetes.io/hostname: neoas1lm-w1
    tolleration:
      - key: node-role.kubernetes.io/laptop
        value: "true"
        effect: NoExecute
