---
# currently this is manually copied to /etc/netplan/99-static-netcfg.yaml
network:
  version: 2
  renderer: networkd
  ethernets:
    enp2s0: {}
    enp3s0: {}
    enp4s0: {}
    enp5s0: {}

  bridges:
    br0:
      interfaces:
        - enp2s0
        - enp3s0
        - enp4s0
        - enp5s0
      dhcp4: no
      dhcp6: no
      parameters:
        stp: true
      addresses: [192.168.1.2/23,192.168.1.1/23] # Description: Management VLAN

  vlans:
    vlan10:
      id: 10
      link: br0
      addresses: [192.168.10.2/23,192.168.10.1/23,"2001:470:ee86:10::2/64"]
      # Description: VLAN for home network
    vlan20:
      id: 20
      link: br0
      addresses: [192.168.20.2/23,192.168.20.1/23]
      # Description: VLAN for iot
    vlan30:
      id: 30
      link: br0
      addresses: [192.168.30.2/23,192.168.30.1/23,"2001:470:ee86:30::2/64"]
      routes:
        - to: default
          via: 192.168.30.1  #floating default route, required for k3s to work
          metric: 200
      # Description: VLAN for k8s
    vlan40:
      id: 40
      link: br0
      addresses: [192.168.40.2/23,192.168.40.1/23]
      # Description: VLAN for untrusted
    vlan999:
      id: 999
      link: br0
      dhcp4: yes
      # Description: VLAN for WAN