---
#41-59 for k8s, 60 for VIP, 61-70 for LB.
kubernetes:
  vars:
    ansible_user: k8s
  children:
    master:
      hosts:
        neohv1vm-m1:
          ansible_host: 192.168.30.41
          ansible_v6host: 2001:470:ee86:30:192:168:30:41
        neohv2vm-m2:
          ansible_host: 192.168.30.42
          ansible_v6host: 2001:470:ee86:30:192:168:30:42
        neobl1bm-m3: #beelink, zfs
          ansible_host: 192.168.30.43
          ansible_v6host: 2001:470:ee86:30:192:168:30:43
    worker:
      hosts:
        neoas1lm-w1:  #lm=laptop machine
          ansible_host: 192.168.30.46
          ansible_v6host: 2001:470:ee86:30:192:168:30:46
        neotc1bm-w2: #tc=thinkcenter, zfs
          ansible_host: 192.168.30.47
          ansible_v6host: 2001:470:ee86:30:192:168:30:47
