---
#41-60 for k8s, 61-70 for LB.
kubernetes:
  children:
    master:
      vars:
        ansible_user: k8s
      hosts:
        k3sne-m1:
          ansible_host: 192.168.30.41
    #    k3s-m2:
    #      ansible_host: 192.168.30.42
    #    k3s-m3:
    #      ansible_host: 192.168.30.43
    worker:
      vars:
        ansible_user: k8s
      hosts:
        k3sne-w1:
          ansible_host: 192.168.30.46
