---
#41-60 for k8s, 61-70 for LB.
kubernetes:
  children:
    master:
      vars:
        ansible_user: k8s
      hosts:
        k3sneo-m1:
          ansible_host: 192.168.30.41
          ansible_v6host: 2001:470:ee86:30:192:168:30:41
        k3sneo-m2:
          ansible_host: 192.168.30.46
          ansible_v6host: 2001:470:ee86:30:192:168:30:46
        k3sneo-m3:
          ansible_host: 192.168.30.47
          ansible_v6host: 2001:470:ee86:30:192:168:30:47
    #worker:
    #  vars:
    #    ansible_user: k8s
    #  hosts:
    #    k3sne-w1:
    #      ansible_host: 192.168.30.46
