---
#41-59 for k8s, 60 for VIP, 61-70 for LB.
kubernetes:
  vars:
    ansible_user: k8s
  children:
    master:
      hosts:
        neok3svm-m1:
          ansible_host: 192.168.30.41
          ansible_v6host: 2001:470:ee86:30:192:168:30:41
        neok3svm-m2:
          ansible_host: 192.168.30.42
          ansible_v6host: 2001:470:ee86:30:192:168:30:42
        neok3sbm-m3:
          ansible_host: 192.168.30.43
          ansible_v6host: 2001:470:ee86:30:192:168:30:43
    worker:
      vars:
        ansible_user: k8s
      hosts:
        neok3slm-w1:  #lm=laptop machine
          ansible_host: 192.168.30.46
          ansible_v6host: 2001:470:ee86:30:192:168:30:46
