apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Hi5/bwkv/6aJCnqk,iv:BPLk1r4lCZsaMChPQ7iyJxXBiiMTgttMaDAU5YTxzWY=,tag:upyoIJQjppJJEU5pQ6neYg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:UwHBcU0RspOdv796ePbK2aPL5dJ8,iv:V36ZbEj5YBHQTtApnl1852XaSqYbhtxAh+M8togX3do=,tag:xdOmP4/z+mbbYFimmVG0kg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Yj0A1fcrz+GLQgl++6r2cAe6/NwLK06wN3Xc+dS8gMKzaFqKJUII1g==,iv:haeM7EAlpCYvD724h0Cn6Qf3YV/wv/C/GgKM6uTfAFY=,tag:b/DcHAXmWEBHxxP/v0qouw==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:v354QfuHrE92KIf7GaBI9Jym2V/jd2MjQ1I4/i7BNoBukxLLNT6OXGxO7wjA7ho=,iv:I4sc2xhPIvOVBkwh+pChwqe6gegp4p4cnlIxbcFhpv0=,tag:pJm3tELUI2qJCUwKruoKWA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:nr5JG7+P7/cO5wvf7xhplLdeSndSnEZf8xoWFhH3,iv:4HHNTsRtC4ZhAE2P1YXmNTjeAx+t3e7vneyuriTJ/l8=,tag:hABvUyJNejFp+05b0sYKkQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:TF/agHFCaNquXUXsjKeC39JaH7I=,iv:3iE91T7TCEqXTVf9DiwbceMMteQch33V1QIPg+oANig=,tag:GwOXfeAYwunChLDOVvKBog==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:vXSOFDcs2f5CwXVmzhYWangEaDQtVQcYrXQ1eywZKOglDxA7ZP0QZA==,iv:xShowPZMiK3/b4yzKQpMJUV4XzWsBa+BNlbsBN4U0C8=,tag:lIjPEfbBYJsTGhsDzgiYlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w8pq3mz7lhcnf3ajppkf9ee9j7ywapkenrads9nk3yjm08szd4rqwy3r67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQTNueHZJR1FadExaT3lF
            YlBMR2FGTW9KUk52UnhqSXdRamR1bjBuc0VnCi9MNUR2dHgzdDlDck45V2ttY0lV
            SFpQVzgrUVJQb1BtZ1VIZzNSNXVPN1EKLS0tIGpmTC9RdkJUb0UwYktlTzNUZTYz
            S2hka3Uyd1JHcTlpc2N3MGlBNERvdEkK6qXEWei4mp5juVOCNk4PfEkc+SjKU5G6
            N25TL6iNZNYfR++Fu877qqTGGGwfU7dmXu0h5Xc7FBDdUymm1dHuyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-25T07:42:33Z"
    mac: ENC[AES256_GCM,data:jQxwyuTpCX1ISs5FH+VrtfbBBwvY6lxTiSDAHdab4JqDPtX2mPdeC7EE4dvXCXTs/7+0iwTQROdaxWMJ40HLqVLQdwJNHNJP6DPgVCUzuwjACozpCMBTbU6q+br+iTukYGXM8vkGgfgSTMfNNzNGLwCSA2/ddhQ2xydQA70cEcA=,iv:rAHxv+4Rge6nxo19TSop5dW0hEFKs+G7vq/bHVt2MAs=,tag:zZvkWNpnwJQTbmqIQ7MO8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
