apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Hi5/bwkv/6aJCnqk,iv:BPLk1r4lCZsaMChPQ7iyJxXBiiMTgttMaDAU5YTxzWY=,tag:upyoIJQjppJJEU5pQ6neYg==,type:str]
    SECRET_ADMIN_EMAIL: ENC[AES256_GCM,data:AAjcjcq8tB9TehDJg/QMsSN9TzKe,iv:d7cRn73VgBzISiLqYbwEDc4lqQ541unB0WISh58T0+M=,tag:HnfzGME9zIHVujzPojLOEA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:7Ts1NsDVG+ZxkBh5jo0tf96CMhPj,iv:wzNe3OY7YXrQIDFbRVEZWnPkEWdEurHlKh8CLaoOrvQ=,tag:sUO9dbnTFrWtpQ1cOo6bEQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Yj0A1fcrz+GLQgl++6r2cAe6/NwLK06wN3Xc+dS8gMKzaFqKJUII1g==,iv:haeM7EAlpCYvD724h0Cn6Qf3YV/wv/C/GgKM6uTfAFY=,tag:b/DcHAXmWEBHxxP/v0qouw==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:tBX2n9GI7T+m0LbA1srsekAbIOJ0mMRUbT0lb8nG59ZfQ81SYQoyerXS,iv:L2X9M2AI6l2QInmIzJyfgQ4X2m/bKTuYUNdZKkkxTww=,tag:PrG/2zfKbpOPLjj85j93NQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:RlBjHaE9OUmP46bbGwZZG7okW6fC69A5u1VypGBY,iv:lGwgUTW5e36A9uuYIgaIU8Y1bGlIHi6eJ4SDt0Zy8hE=,tag:ZYG4pgIdqa2iFvswVOmWkQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ygbpuH6DVdYcESiejCQDgItMidM=,iv:QohbjBQmtWjOzZPg5OX0ri/pYiZICmuG3lKbt4P9wto=,tag:2Qb591ZJXbz7fuAGSa3zYw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:N2Dw/yWfIedbqNsgOiqXdBJQyBcs62E4p0/Gj6GJGmDKq4AGW6KNDQ==,iv:71vD3bqjAs/K59PFsnO4O+LSV7zzWRMA98+GlQFSBmc=,tag:l7fLwGscuPSevgETYFA+Xg==,type:str]
    MINIO_ENDPOINT: ENC[AES256_GCM,data:6gCGdBuIEbzLCWhHE2nEItVCd0mtvurLeMXUn1uP,iv:pPCV0ODcBjikhejF80EiQBPlWYo2vmtAFvQkLWoAQXg=,tag:gMY76z+wHMBBbYinL0F59w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w8pq3mz7lhcnf3ajppkf9ee9j7ywapkenrads9nk3yjm08szd4rqwy3r67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQTNueHZJR1FadExaT3lF
            YlBMR2FGTW9KUk52UnhqSXdRamR1bjBuc0VnCi9MNUR2dHgzdDlDck45V2ttY0lV
            SFpQVzgrUVJQb1BtZ1VIZzNSNXVPN1EKLS0tIGpmTC9RdkJUb0UwYktlTzNUZTYz
            S2hka3Uyd1JHcTlpc2N3MGlBNERvdEkK6qXEWei4mp5juVOCNk4PfEkc+SjKU5G6
            N25TL6iNZNYfR++Fu877qqTGGGwfU7dmXu0h5Xc7FBDdUymm1dHuyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-22T01:28:18Z"
    mac: ENC[AES256_GCM,data:xQIobMUujxNJKRCN9IRDMefCjUe04wihnWD6Re/JcWgLB/bjc4stDzfVgmzQeODgKWUbKqf8zwWyhOV2eqxWf9qFdh5PjG2gb0yttwMfwmUJK5bKGCPwg/co2EtU9GJupluGNpOQM9pChxrgnhI0WIfp59yGZsXtURboHzUeXEw=,iv:OG9A+82lCQN5WpWMPkwzF1ArblR5QieWF5S414KSED4=,tag:FNUQ5HsY7h0FlU9PICKFpA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
