apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Hi5/bwkv/6aJCnqk,iv:BPLk1r4lCZsaMChPQ7iyJxXBiiMTgttMaDAU5YTxzWY=,tag:upyoIJQjppJJEU5pQ6neYg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:UwHBcU0RspOdv796ePbK2aPL5dJ8,iv:V36ZbEj5YBHQTtApnl1852XaSqYbhtxAh+M8togX3do=,tag:xdOmP4/z+mbbYFimmVG0kg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Yj0A1fcrz+GLQgl++6r2cAe6/NwLK06wN3Xc+dS8gMKzaFqKJUII1g==,iv:haeM7EAlpCYvD724h0Cn6Qf3YV/wv/C/GgKM6uTfAFY=,tag:b/DcHAXmWEBHxxP/v0qouw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w8pq3mz7lhcnf3ajppkf9ee9j7ywapkenrads9nk3yjm08szd4rqwy3r67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQTNueHZJR1FadExaT3lF
            YlBMR2FGTW9KUk52UnhqSXdRamR1bjBuc0VnCi9MNUR2dHgzdDlDck45V2ttY0lV
            SFpQVzgrUVJQb1BtZ1VIZzNSNXVPN1EKLS0tIGpmTC9RdkJUb0UwYktlTzNUZTYz
            S2hka3Uyd1JHcTlpc2N3MGlBNERvdEkK6qXEWei4mp5juVOCNk4PfEkc+SjKU5G6
            N25TL6iNZNYfR++Fu877qqTGGGwfU7dmXu0h5Xc7FBDdUymm1dHuyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-27T13:05:14Z"
    mac: ENC[AES256_GCM,data:FCbeTVqsBx6qLaqqrId7xXJ1Ph2cispaWf+DR5MvZctO6PoCXlI579HiAv42jKibFn4qUlDr8wRnaQjCrUZXtWcfxCXmyVL3EaFavNJ7Z8eIB/CNA8xp5Cvm4WtknktuL/JjI4r1uMHdaPb7lYj9hO4mscGAo99EPDW/Xdxnwdc=,iv:vxFEbaqJxg45M6X43ZiC37+OctkBTIa0I3CmbPeF66I=,tag:CAMm5+FkCept0nmenHHyVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
