apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:SZc4/ZvQ/KSMwT6gVn69QcuX5rS9oQ1sUGxKBnAeEc4Y5pR48iInt3ZQVXDxX7lHYFBCFGDPMI9gxxfb,iv:BnITFSXDThcCtDkm87K0LYCiCT3tVd2uHzfIuaXNkGw=,tag:DBCYxtSYg6WRfJP50R7JaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w8pq3mz7lhcnf3ajppkf9ee9j7ywapkenrads9nk3yjm08szd4rqwy3r67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbmNSdkN1eFNRSDFITlIw
            N0FuU0twUHJ4UVoyRFlVN3QvWFRHUldkL2xNCmdkSXN2RTNNa3FFOUVrYU1zdnZ3
            VTErLzdnZ2F6UmJuNzJpeUE3U2dLamsKLS0tIFdES0tyY0ZrMzUvaVlsUGlObVN5
            VGdjVGJ5ellKVU9FTm5LNDlDWWhwNTQK3aVCYiDv1GsslXjN7C86NaWXsKMRMjqZ
            quplwS3zvyIHiRV3VkRfjGU/izm5BDiQCkIjNDpmAjOOY14PZmZr8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-04T11:50:55Z"
    mac: ENC[AES256_GCM,data:+22cW71pCwHLjiHvLM3C4Vcu2w/iRbi8+S6TcsRwK5IasUKAEH06S/e42taxIrB+jWQiaKD9YcVZt3ZuZAktz1AoE2xtxrAShjeGAz0JgDplDKWSKy2zf57Prarpadqnt0bffTsgICvnO37Fhz/+8GlqqAEQCu5aDDbxUg7+9Rw=,iv:qrkz5Vn9DYsRgB0VMhMQQ+z9ogG823lxoWkAKQ5xlp8=,tag:1b1zFd+tcPt6NT+dGbHZsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
