apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:tFllwSyED8tpMnKGrqXMuWIIQjZwTSE=,iv:EO7PbddjjEJMGEuHY0Klcsfqs29cnQRI4xlldyomUps=,tag:dAaKmroys/vsBSPjGekm/A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:2lJCWyVSxGNH0SY0W7XeClzyED9+,iv:z7rapss+McrpPAhKxx7CmiCoZbiOSw8SLzvcdT9YKxU=,tag:nouTh552Xky/wa8S1nocUg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:zZSAB5DmQ5v0JMKrkXyd3dzw7w9LW/CagpDxwj9yE23LcdEs,iv:Rcujjp3r1oHDKENIqMazbG1xKP/XFu87H/teP0JkKBM=,tag:0gl+JrPrvG3C3OL+HlGu6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w8pq3mz7lhcnf3ajppkf9ee9j7ywapkenrads9nk3yjm08szd4rqwy3r67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZW8zRGVrTFJ6aGNqWndC
            Ym0wTG1RTDVXZ2lRMXo4WWtBUHhNcFp3MzNRCmgvRmNXUWRTSFBYaG54NlhPMlBa
            VUQwNmJ2U3BBYWhBYXNrUDRmcjd6MlUKLS0tIGRJaDFBOWltV3ZVOXdVeXlrNXY5
            NlpPR0UwM0FpS3FOUXlVRldMc2tSeEUKXxbhUDgf/feNdv8hD+ULAAYFE9C2xdI/
            Iho0Hi4XgB9ZFqFzLc8tauKGMB5S+iMnRFzCnJrOvvkZLl0cOnH37A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-23T09:45:39Z"
    mac: ENC[AES256_GCM,data:sOFss7uOS/2HSKyFjwL/cflJMjM7mgWyd7Ij+4kjyX4EJEeRHcyMByCV8QVf4OwAGkt8W2vXewygpNdMlp6UrTceXpeblZ7zkwgEN9SvFrjJk+BjPw8ax/uvdmjOxjtiFmdkRq2dr4nQIPXmTE0QzLVoyrzJIiDHSfXldn5T9Lo=,iv:HncgS2kgHfk5j5PsimtWz/TfkqhkY1Pt3d+tbBuQWHk=,tag:OWvJUvECx89cSjDgD19UEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
