apiVersion: v1
kind: Secret
metadata:
    name: photoprism-secret
stringData:
    PHOTOPRISM_ADMIN_PASSWORD: ENC[AES256_GCM,data:a4r/1thruL1G4zar,iv:r+6MpLknA/fTEcqrvlotaDpoQL5PNqoKms6FXGhDZbY=,tag:j8+D9I4hwKgfHyVtxTgzmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w8pq3mz7lhcnf3ajppkf9ee9j7ywapkenrads9nk3yjm08szd4rqwy3r67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQTdETG05U2RwMCtYWFZG
            eXcySnNVSE5UeG9SWXNkTlNmRVNtRU94dVFvCmZ4OGdoYU1ycStGRE5TVGU4SkNY
            K1JPS2d1dDlHY0hXSjZsek5USzE2Tm8KLS0tICs3WmNab1Y0bjhWOC90UFltTlRJ
            SHQxZmtXeGhadU1BeEF6UEVadHVGVjQK2JypgghHwuBDE29MhtKieSGK6hbShF7R
            LHacj+5hFXA1izqVUzs7gFQSjUgyfwUuUpWNKIWerTiKbuF4tJWJGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-04T13:29:42Z"
    mac: ENC[AES256_GCM,data:RCMf9Q/adxu0YrwuTUc3Qcs+jFj0ImmHKIPHZly/u7iSdCrIGrQ/gV3RHCZlT4ok7FjpfNghiRPh1yg6XCM/ShlurFoGKo+j4plPEkNv0VqXJ9276kEZShc1J/xzhivypSHIxBtfnNCvjJx2L5aP/cSnsPIWMyyVSIANkolN6qY=,iv:vMAUWr2LMU7tAW3+ItlZTRet+7RkzSyjD5Xb3PodHAY=,tag:zajSosj5cTalaK3By9hCUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
