apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:iB+sezGcNn8FxnuzHgbgbPApzLiYnFC/MKqAD32J8zuvmCGw,iv:c9tF7SXmmzL3N0s5ZLRqQws445ZRxjyMuvRApp6nqBA=,tag:BjNbDTjJpzENOAmhgbL2xg==,type:str]
    credentials.json: ENC[AES256_GCM,data:RaWJxRM/Jw60GA/Xhjb6ix/7khJCSP3MbihVvjhRSXcfWUb0dCNdEIFz8uBt/FiGmuWVYvXRhbYZvyYEpLPsjJ3ZN/uTuHi9kLyn4l4420NMP1j0iE59GIMSGEmbTtgtcaXxNQrylkoDwBg6mZhPqZtIbVvtzvK7GeJG00G4UpSRIG9U8ashleDluvsoQ8YqTPxvInAzZMULm24J9KJLYJcm1aLZWm0ChIaj52EcBw==,iv:TroEAIwyGKBtHPWSGov1DeLvsLbzNe34jxrm5xBzIAc=,tag:9l5kuD8bT4n2yt5cEL88pA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w8pq3mz7lhcnf3ajppkf9ee9j7ywapkenrads9nk3yjm08szd4rqwy3r67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSKzFFd0hGeUpWcVRqOU0r
            aGJzbjI0V3BjU1V2QkRCeHk5NjNGWXdXMVI0CnRhQjJ0VlE2M01xSWxJUGVUWS91
            NmVubmY4V0VVUVVTbkN2bDR3RHcrUUUKLS0tIFdCbi9RdmFCdkxNUVJxcVdJc2Zk
            cGdPQ2o1SFR5OC9paTJVOHJtUmJoRzgKTGbmGxc71oDHEzzrDp06yAeyjjKtsRIP
            s7kZEHjFOLXpZUmtn49ggkU4Jg9pdvLW++BM15/EUoYSEmDIQFJvVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-04T11:50:55Z"
    mac: ENC[AES256_GCM,data:iuKZI9ImwaPEnQrEJdfGopbl+/vxG+RLuvsLpfsE22ruHUSIWGPktVDLjc6E0C8unSQE0rn/9Mp/Ib550ggAv3WMbd7RSB/fCdIl4Bs1eiYNaJnwFFZcbAWj08UiXkowCQhOhOo3NHa7bBMwzs76ac3DF7BN4x7ZUroEvFDjfCo=,iv:74GxMqNh5RLlurVWHuVKJUoS8z4qiVPEkM6y5H8i/Z8=,tag:jGnzzyWRi2AamJVHoK4Nsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
