---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app multus
  namespace: flux-system
spec:
  targetNamespace: network
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: "./kubernetes/neo/apps/kube-system/multus/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
#---
## yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: &appname multus-config
#  namespace: flux-system
#spec:
#  targetNamespace: network
#  commonMetadata:
#    labels:
#      app.kubernetes.io/name: *appname
#  interval: 10m
#  path: "./kubernetes/main/apps/network/multus/config"
#  prune: true
#  sourceRef:
#    kind: GitRepository
#    name: home-ops-kubernetes
#  wait: true
#  dependsOn:
#    - name: multus
