---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-gateway
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  path: "./kubernetes/apps/networking/istio-ingress/app"
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: cluster
  dependsOn:
    - name: istiod
      namespace: flux-system
    - name: cert-manager
      namespace: flux-system
