---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-istiod
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  path: "./kubernetes/neo/apps/networking/istio/istiod/app"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
  dependsOn:
    - name: cluster-apps-istio-base
      namespace: flux-system
