---
timezone: "Asia/Singapore"
github_username: abasitt
kubeapi_addr: "2001:470:ee86:30:192:168:30:41"
cluster_cidr: "10.44.0.0/16"
cluster_v6cidr: "2001:470:ee86:1044::/56"
service_cidr: "10.45.0.0/16"
service_v6cidr: "2001:470:ee86:4:10:45::/112"
coredns_v4addr: "{{ service_cidr.split(',')[0] | ansible.utils.nthhost(10) }}"
coredns_v6addr: "{{ service_v6cidr.split(',')[0] | ansible.utils.nthhost(10) }}"
nodes_v4cidr: "192.168.30.0/24"
nodes_v6cidr: "2001:470:ee86:30::/64"
