---
# https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/
# https://github.com/PyratLabs/ansible-role-k3s

k3s_control_node: true
k3s_server:
  node-ip: "{{ ansible_host }},{{ ansible_default_ipv6.address }}"
  #node-ip: "{{ ansible_default_ipv6.address }},{{ ansible_host }}"
  tls-san:
    - "{{ kubevip_address }}"
    - "{{ ansible_default_ipv6.address }}"
  docker: false
  flannel-backend: "none"             # This needs to be in quotes
  disable:
    - flannel                         # Disable flannel                 - replaced with Cilium
    - local-storage                   # Disable local-path-provisioner  - installed with Flux
    - metrics-server                  # Disable metrics-server          - installed with Flux
    - servicelb                       # Disable servicelb               - replaced with metallb and installed with Flux
    - traefik                         # Disable traefik                 - replaced with ingress-nginx and installed with Flux
  disable-network-policy: true
  disable-cloud-controller: true
  disable-kube-proxy: true            # Cilium uses eBPF
  write-kubeconfig-mode: "644"
  # Network CIDR to use for pod IPs
  cluster-cidr: "{{ cluster_cidr }},{{ cluster_v6cidr }}"
  service-cidr: "{{ service_cidr }},{{ service_v6cidr }}"
  kubelet-arg:
    - "feature-gates=GracefulNodeShutdown=true"
    - "feature-gates=MixedProtocolLBService=true"
    - "node-status-update-frequency=4s"
  kube-controller-manager-arg:
    - "bind-address=0.0.0.0"          # Required to monitor kube-controller-manager with kube-prometheus-stack
    # https://github.com/k3s-io/k3s/issues/1264
    - "node-monitor-period=4s"
    - "node-monitor-grace-period=16s"
  kube-scheduler-arg:
    - "bind-address=0.0.0.0"          # Required to monitor kube-scheduler with kube-prometheus-stack
  etcd-expose-metrics: true           # Required to monitor etcd with kube-prometheus-stack
  kube-apiserver-arg:
    - "anonymous-auth=true"           # Required for HAProxy health-checks
    - "default-not-ready-toleration-seconds=20"
    - "default-unreachable-toleration-seconds=20"
