---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
#  - egress-gateway/ks.yaml
  - ingress-gateway/ks.yaml
  - ingress-privategateway/ks.yaml
  - ingressclass.yaml
