---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-gateways
  labels:
    istio-discovery: enabled
    istio.io/dataplane-mode: ambient
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
