---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./alertmanager-secrets.secret.sops.yaml
  - ./helmrelease.yaml
  - ./httproutes.yaml
  - ./prometheusrules

configMapGenerator:
  - name: kps-helm-values
    files:
      - values.yaml=./helm-values.yaml
  - name: alertmanager-config-tpl
    files:
      - alertmanager.yaml=./alertmanager.yaml
generatorOptions:
  disableNameSuffixHash: true

configurations:
  - kustomizeconfig.yaml
