apiServer:
  enabled: false
  apiServerDeployment:
    spec:
      template:
        spec:
          containers:
            - name: calico-apiserver
              resources:
                limits:
                  cpu: 50m
                  memory: 200Mi
# Configures general installation parameters for Calico. Schema is based
# on the operator.tigera.io/Installation API documented
# here: https://projectcalico.docs.tigera.io/reference/installation/api#operator.tigera.io/v1.InstallationSpec
installation:
  enabled: true
  registry: quay.io
  imagePath: calico
  calicoNetwork:
    bgp: Enabled
    linuxDataplane: Iptables
    # https://projectcalico.docs.tigera.io/networking/ip-autodetection
    nodeAddressAutodetectionV4:
      cidrs:
        - ${NODES_V4CIDR}
    nodeAddressAutodetectionV6:
      cidrs:
        - ${NODES_V6CIDR}
    # Note: The ipPools section cannot be modified post-install.
    ipPools:
      - blockSize: 116
        cidr: ${CLUSTER_V6CIDR}
        encapsulation: "None"
        natOutgoing: Enabled
        nodeSelector: all()
      - blockSize: 26
        cidr: ${CLUSTER_CIDR}
        encapsulation: "None"
        natOutgoing: Enabled
        nodeSelector: all()
  nodeMetricsPort: 9091
  typhaMetricsPort: 9093
kubeletVolumePluginPath: None
resources:
  requests:
    cpu: 15m
    memory: 96Mi
  limits:
    cpu: 500m
    memory: 196Mi
