---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-istio-ingress
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  path: "./kubernetes/apps/networking/istio/istio-gateways/ingress-gateway/app"
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: istiod
      namespace: flux-system
    - name: cert-manager
      namespace: flux-system
