apiVersion: v1
kind: Secret
metadata:
    name: calibre-volsync
type: Opaque
stringData:
    #ENC[AES256_GCM,data:/hEfYeeawCIrufCcfDzvq0rn/A==,iv:AzTC28kDS+0a/19z0dkj1RtRBU2Ssl/bOAaxnYfvXjk=,tag:H5bRk8GjEPSSSyCeeAi50g==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:FZ8Oi6oxVBj+sA/VX/tt3PRUgL43ev1EiWmFAP7IUYg8qPdUXUNUFbhLqj3f,iv:Vn1O5g29vbcoy3Fdbw2tewQN1bEXZQl/DHDQS2aDHX4=,tag:hlBfQmQ0aAtejdmR8OJHWQ==,type:str]
    #ENC[AES256_GCM,data:JDP9zG4vbB6J4XQYOS00fT8B2067oak4USzs7d2f,iv:U3wMD+ssg7ArQkCU0ds5WZc79kr+d3QE6IK7qakA0dU=,tag:Y7PERvnDxD7iNliFi/rX7Q==,type:comment]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:vNg+tANQN1Pq/KZvsGwmhnLZ,iv:hn5JuBQronQZsFOY4UT6k+NR7pvysBz8Z51XgmQI6To=,tag:5BY82vfaoTa4kHfzbfP40w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:+/YvTAhfEnTPuJYjTpXRMW8VWZQ=,iv:mJ28UJRae6srx+HP1ODjjjuaV3ziKnrH9XxLtuh1Uu0=,tag:e7Ax3SAOJ7mpQ76MHwx8Gg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:RXOxg2YNfRft2qYJpA2kLsW/i/jLHtg2,iv:7fEJmXhfx3cYsMdT5FLrn5fxETbQX92tiW78cZEmDbw=,tag:6vR/ezGI1g6PCwn6LAAanw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w8pq3mz7lhcnf3ajppkf9ee9j7ywapkenrads9nk3yjm08szd4rqwy3r67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSzUrVUo3bUJKSytXL01U
            Mnh6aUFWYW1iOERDOEhjNTZ0V2h1Ni95UUZvCk5jRXpxNjVzY2Rra1RrSkJ2eGh0
            SnJkckIxL3ZVNVNsK1NBTjBQR2RZeWsKLS0tIG1nOVZ2Z0ZsaXhzdXFIbGk5cmow
            ZTlSNGpBb0RnelkvUWtteE5HV21iQkEKt9htCHwtxAYwlFjjRZrCJvBHNhdOgz0V
            GQENgtPKY6E9LVB7BhG1JRwm2N09SuAPbt7Ye3FOKQWDWMwxN3yF8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-27T13:39:47Z"
    mac: ENC[AES256_GCM,data:a4kn6oFXAcigwgLtrHxUPJHiV/vFPN3vw7N/K428SrXfjn60O0Je3fjYi3SBPjFIAEMsni4p386obsfJPgIQCOdhQNgEBk7kUGyCmmxQZeSRQIDl+mZu4sxaslxJoAhu8hmUnVuLdqCBb2QRTGC+sQrn689kXLKAsQhRuIVnksg=,iv:RbqGuQoWDGM8VgWCbDvWOmflMrEpWbspRsyzbclf98s=,tag:7SFzwrt7kd2OCSLSqx9gzw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
