---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: cnpg-cluster16
spec:
  parentRefs:
  - name: private-gateway
    namespace: istio-gateways
    sectionName: tcp-cnpgcluster16
  rules:
  - backendRefs:
    - name: postgres16-rw
      port: 5432
      kind: Service
