---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: postgres-cluster16-tcproute
spec:
  parentRefs:
    - name: postgres-cluster16-gateway
  rules:
    - backendRefs:
        - name: postgres16-rw
          port: 5432
          kind: Service
